### ISSUE TITLE
Non-stationary style loss

### ISSUE THREAD

**Issue by alexjc** [jcjohnson/neural-style#10]
A few of us noticed the algorithm should take into account semantics, and someone pointed out to me on Twitter that convolutional networks already include semantic information—of course!  What's missing is to adapt loss in the lower levels (style) based on the higher levels (semantics) dynamically.

I'm not sure how to do this yet, but I figured I'd post it here to start the discussion :-)

**Comment by jcjohnson** [comment]
I'm not sure how you might implement that, but let me know if you have ideas!
