### ISSUE TITLE
attempt to index global 'neural_style' (a nil value)

### ISSUE THREAD

**Issue by Vindic2** [jcjohnson/neural-style#101]
Hello,

I checked the corresponding issues and tried various things but still get that error :

`th> neural_style.lua `
`[string "_RESULT={neural_style.lua }"]:1: attempt to index global 'neural_style' (a nil value)
stack traceback:
	[string "_RESULT={neural_style.lua }"]:1: in main chunk
	[C]: in function 'xpcall'
	/home/leo/torch/install/share/lua/5.1/trepl/init.lua:650: in function 'repl'
	.../leo/torch/install/lib/luarocks/rocks/trepl/scm-1/bin/th:199: in main chunk
	[C]: at 0x00406670	`

Does not look like a laodcaffe issue though :
`th> require 'loadcaffe'`
`{
  load : function: 0x40fc1bf0
  C : userdata: 0x4111c548
}`

**Comment by TT--** [comment]
how did you resolve this?

**Comment by htoyryla** [comment]
@TT--  You can't simply type the name of the script inside torch interpreter, it will then assume neural_style is a variable which is nil. Run neural-style from the command line as described in the instructions.
