### ISSUE TITLE
GPU is not used

### ISSUE THREAD

**Issue by JFixby** [jcjohnson/neural-style#102]
Hello,
I have a performance problem.

Setup: GeForce GT 630M with  2Gb of video memory

Scenario 1: process image with -image_size=360
- processing takes ~90 minutes,
- crashes on bigger images,
- ```nvidia-smi``` shows that ~1.3Gb of video memory used while the GPU seems is not occupied (is it processing with CPU?)

Scenario 2: running the same with ```-gpu -1`` flag
- ok for bigger images
- works a bit faster
- ```nvidia-smi``` shows that video memory is not used

Is it a bug?

**Comment by jcjohnson** [comment]
My guess is that the GPU is being used; however the 630M is a pretty weak GPU so it may not be faster than running in CPU mode.

**Comment by JFixby** [comment]
This sounds very probable. So I closed.
