### ISSUE TITLE
[feature request] Grayscale (Black&White) content + colored style?

### ISSUE THREAD

**Issue by JFixby** [jcjohnson/neural-style#105]
Should save some memory/performance.

**Comment by jcjohnson** [comment]
This won't actually save any memory or computation because the grayscale image would need to be fed through the pretrained VGG network; see additional discussion here:

https://github.com/jcjohnson/neural-style/issues/82

**Comment by JFixby** [comment]
Yep.
I think also it would miss color palette mapping info (where reddish colors mapped to reddish and so on).
