### ISSUE TITLE
Module 'nn-cpu' not found.

### ISSUE THREAD

**Issue by Erdromian** [jcjohnson/neural-style#106]
After installing the project dependencies on ubuntu 14.04.3 I get the following results from running the example command:
austin@austin-ubuntu:~/neural-style$ th neural_style.lua -gpu -1
[libprotobuf WARNING google/protobuf/io/coded_stream.cc:505] Reading dangerously large protocol message.  If the message turns out to be larger than 1073741824 bytes, parsing will be halted for security reasons.  To increase the limit (or to disable these warnings), see CodedInputStream::SetTotalBytesLimit() in google/protobuf/io/coded_stream.h.
[libprotobuf WARNING google/protobuf/io/coded_stream.cc:78] The total number of bytes read was 574671192
Successfully loaded models/VGG_ILSVRC_19_layers.caffemodel
/home/austin/torch/install/bin/luajit: /home/austin/torch/install/share/lua/5.1/trepl/init.lua:383: module 'nn-cpu' not found:No LuaRocks module found for nn-cpu
	no field package.preload['nn-cpu']
	no file '/home/austin/.luarocks/share/lua/5.1/nn-cpu.lua'
	no file '/home/austin/.luarocks/share/lua/5.1/nn-cpu/init.lua'
	no file '/home/austin/torch/install/share/lua/5.1/nn-cpu.lua'
	no file '/home/austin/torch/install/share/lua/5.1/nn-cpu/init.lua'
	no file './nn-cpu.lua'
	no file '/home/austin/torch/install/share/luajit-2.1.0-beta1/nn-cpu.lua'
	no file '/usr/local/share/lua/5.1/nn-cpu.lua'
	no file '/usr/local/share/lua/5.1/nn-cpu/init.lua'
	no file '/home/austin/.luarocks/lib/lua/5.1/nn-cpu.so'
	no file '/home/austin/torch/install/lib/lua/5.1/nn-cpu.so'
	no file './nn-cpu.so'
	no file '/usr/local/lib/lua/5.1/nn-cpu.so'
	no file '/usr/local/lib/lua/5.1/loadall.so'
stack traceback:
	[C]: in function 'error'
	/home/austin/torch/install/share/lua/5.1/trepl/init.lua:383: in function 'require'
	models/VGG_ILSVRC_19_layers_deploy.prototxt.lua:1: in main chunk
	[C]: in function 'dofile'
	...stin/torch/install/share/lua/5.1/loadcaffe/loadcaffe.lua:24: in function 'load'
	neural_style.lua:69: in function 'main'
	neural_style.lua:495: in main chunk
	[C]: in function 'dofile'
	...stin/torch/install/lib/luarocks/rocks/trepl/scm-1/bin/th:145: in main chunk
	[C]: at 0x00406670

I have done the exact same procedure on my laptop in ubuntu 15.10 and have everything running fine.  Does anyone know what I might be missing or could try?

**Comment by jcjohnson** [comment]
Sorry about that - I merged some pull requests earlier today and accidentally introduced a bug. This should be fixed in https://github.com/jcjohnson/neural-style/commit/f36729be1ab249df434755c580ecc314743cdf54; try it again and let me know if it works.

**Comment by Erdromian** [comment]
Yup, that fixed it.  Thanks so much.  This project is so cool!  I am using it to give my art friends some stylized images as Christmas presents.
