### ISSUE TITLE
Device doesn't exist at ..

### ISSUE THREAD

**Issue by Keloo** [jcjohnson/neural-style#107]
th neural_style.lua -style_image examples/inputs/picasso_selfport1907.jpg -content_image examples/inputs/brad_pitt.jpg -output_image profile.png -model_file models/nin_imagenet_conv.caffemodel -proto_file models/train_val.prototxt -gpu 0 -backend clnn -num_iterations 1000 -seed 123 -content_layers relu0,relu3,relu7,relu12 -style_layers relu0,relu3,relu7,relu12 -content_weight 10 -style_weight 1000 -image_size 512 -optimizer adam

/usr/local/bin/luajit: neural_style.lua:57: Device doesnt exist at /tmp/luarocks_cltorch-scm-1-1898/cltorch/cltorch/src/init.cpp:56
stack traceback:
	[C]: in function 'setDevice'
	neural_style.lua:57: in function 'main'
	neural_style.lua:499: in main chunk
	[C]: in function 'dofile'
	/usr/local/lib/luarocks/rocks/trepl/scm-1/bin/th:145: in main chunk
	[C]: at 0x00406260

Can anyone help plz.

**Comment by jcjohnson** [comment]
Looks like you don't have a CUDA capable GPU. Add the flag -gpu -1 to run
in CPU mode.

**Comment by Keloo** [comment]
The driver for Amd Radeon was not installed :)
