### ISSUE TITLE
Clearer installation instructions?

### ISSUE THREAD

**Issue by bestguy** [jcjohnson/neural-style#11]
This is more of a luarocks & torch issue, but it's really not clear how to run this project if you are not a Lua expert :-)

Installing any of the dependencies via luarocks on MacOSX:

    luarocks install ***whatever***
    
    Error: No results matching query were found.

**Comment by alexjc** [comment]
I ran into the same problem on Linux, maybe the luarocks folder (cache) is read only or owned by root.

Try following the instructions to install Torch from their site first (`wget` then `install.sh`), then use the built-in luarocks.

**Comment by bestguy** [comment]
Thanks for the help, trying now.

Have to laugh that even `use built-in luarocks` is confusing me :-), I see 10 luarocks in my torch dir:

```
./build/exe/luajit-rocks/luarocks
./build/exe/luajit-rocks/luarocks/src/bin/luarocks
./build/exe/luajit-rocks/luarocks/src/luarocks
./exe/luajit-rocks/luarocks
./exe/luajit-rocks/luarocks/lfw/lua/luarocks
./exe/luajit-rocks/luarocks/src/luarocks
./install/bin/luarocks
./install/etc/luarocks
./install/lib/luarocks
./install/share/lua/5.1/luarocks
```

**Comment by alexjc** [comment]
If you run `install/bin/luarocks` it'll install things in that local directory.

**Comment by bestguy** [comment]
Got it, thanks for this.   Closed the issue, but if you happen to know the resolution to this loadcaffe installation issue would appreciate the help:

```
-- Could NOT find PROTOBUF (missing:  PROTOBUF_LIBRARY PROTOBUF_INCLUDE_DIR) 
CMake Error: The following variables are used in this project, but they are set to NOTFOUND.
Please set them or make sure they are set and tested correctly in the CMake files:
PROTOBUF_LIBRARY (ADVANCED)
    linked by target "loadcaffe" in directory /tmp/luarocks_loadcaffe-1.0-0-5782/loadcaffe
```

**Comment by bestguy** [comment]
Got it.  For other's reference, fixed by:

`brew install protobuf`

**Comment by kenzan100** [comment]
@bestguy thank! you saved my day.

**Comment by hydrophilicsun** [comment]
+1 👍

**Comment by hhassanzadeh** [comment]
Hi everyone,
I've run into the same problem, I wonder if anyone knows what is the issue.
So basically I'm installing loadcaffe on cluster with NO root access. I could install the protobuf successfully( luarocks install protobuf), however, when I try to install the loadcaffe itself I get the following error:

-- Could NOT find PROTOBUF (missing:  PROTOBUF_LIBRARY PROTOBUF_INCLUDE_DIR) 
CMake Error: The following variables are used in this project, but they are set to NOTFOUND.
Please set them or make sure they are set and tested correctly in the CMake files:
PROTOBUF_LIBRARY (ADVANCED)
    linked by target "loadcaffe" in directory /tmp/luarocks_loadcaffe-1.0-0-73/loadcaffe

-- Configuring incomplete, errors occurred!
See also "/tmp/luarocks_loadcaffe-1.0-0-73/loadcaffe/build/CMakeFiles/CMakeOutput.log".
See also "/tmp/luarocks_loadcaffe-1.0-0-73/loadcaffe/build/CMakeFiles/CMakeError.log".
make: *** No targets specified and no makefile found.  Stop.

Error: Build error: Failed building.

**Comment by johnhany** [comment]
@hhassanzadeh I think you should check the "Advanced" check box before the "Add Entry" button. After that, you can see all the configurations related to protobuf, protoc and protobuf-lite. You can then specify each lib file accordingly, both for release and debug. It worked for me when I tried to compile Caffe after bumping into the same problem, though.

**Comment by prashanth-srinivasan** [comment]
@hhassanzadeh , did you manage to solve this issue? 
I get the same error too.

**Comment by hhassanzadeh** [comment]
Hey, no I could not do that .

**Comment by eldem** [comment]
set the following env variables: 
CMAKE_INCLUDE_PATH = [YOUR_PATH]\protobuf\src\google\protobuf # which points at the bottom of your include path.
CMAKE_LIBRARY_PATH = [YOUR_PATH]\protobuf\src\.libs #which should contain "libprotobuf" "libprotobuf-lite" "liteprotoc" .lib files.

You might also need to add protobuf ([YOUR_PATH]\protobuf\src) to your $PATH system variable if you are on Windows.

Now run cmake: 
cmake .. -G "MSYS Makefiles" # Replace 'MSYS' if you are using a different generator.
