### ISSUE TITLE
16-layer VGG Face Model

### ISSUE THREAD

**Issue by 3DTOPO** [jcjohnson/neural-style#111]
I thought it would be interesting to see what the 16-layer VGG face model does:

http://www.robots.ox.ac.uk/~vgg/software/vgg_face/

I tried it with a couple different 16-layer prototxt model files I found (links below):

    th neural_style.lua -proto_file models/VGG_ILSVRC_16_layers_deploy.prototxt -model_file VGG_ILSVRC_16_layers.caffemodel  -gpu 0 -backend cudnn

Either way I get this error:

    Couldn't load VGG_ILSVRC_16_layers.caffemodel
    /home/prime/torch/install/bin/luajit: neural_style.lua:79: attempt to index a nil value
    stack traceback:
    	neural_style.lua:79: in function 'main'
    	neural_style.lua:490: in main chunk
    	[C]: in function 'dofile'
    	...rime/torch/install/lib/luarocks/rocks/trepl/scm-1/bin/th:145: in main chunk
    	[C]: at 0x00406670

Do I need to generate .lua files like the other prototxt files have? I couldn't quite figure out how to write one by hand at first glance.

I looked and all the same content and style layer names used in the default 19 layer model appear to be present. 

https://github.com/samim23/NeuralTalkAnimator/blob/master/python_features/VGG_ILSVRC_16_layers_deploy.prototxt.txt
https://gist.githubusercontent.com/ksimonyan/211839e770f7b538e2d8/raw/0067c9b32f60362c74f4c445a080beed06b07eb3/VGG_ILSVRC_16_layers_deploy.prototxt

**Comment by 3DTOPO** [comment]
Doh! I was missing the correct path for the model file. Its works! Here is the default test render after 800 iterations. Definitely different and definitely interesting!

Next I will see what it does with faces present. ;)

![test_800](https://cloud.githubusercontent.com/assets/352383/12103529/18828ca2-b300-11e5-81d8-073b780d7b0c.png)

**Comment by sheerun** [comment]
@3DTOPO Could you post your results here? I'm really interested :)

**Comment by 3DTOPO** [comment]
Sure. Here are two renders from two models with default settings using the test brad pitt image and the example 1907 Picasso Self Portrait. The first image used the default 19-layer model. The second image used the 16-layer face model. Personally I think the results are much improved - while being more true to the reference style.

![brad_19](https://cloud.githubusercontent.com/assets/352383/12123686/9bfff020-b39f-11e5-8eae-5883bfbf9208.png)
![brad_16](https://cloud.githubusercontent.com/assets/352383/12123691/a1f8d406-b39f-11e5-80f6-6eefd952d81a.png)

**Comment by djdjoko** [comment]
Did you notice any difference in speed and memory consumption?

**Comment by 3DTOPO** [comment]
Seems slightly faster and uses slightly less memory (~90MB for 640x480 image).

**Comment by djdjoko** [comment]
Very interesting and thanks for posting! Did you by any chance do the
standard image set for the thubingen photo (starry night,scream etc)?

**Comment by djdjoko** [comment]
Also are you sure it uses only 90MB VRAM on that  size? I remember this resolution using more around 2GB

**Comment by 3DTOPO** [comment]
It uses less that amount of RAM; so correct around 2GB.

I didn't have them rendered but here they are. For comparison, the first image is from the standard 19-layer mode, 2nd image  from the 16-layer face model.

![starry_19](https://cloud.githubusercontent.com/assets/352383/12124850/0954daa0-b3a5-11e5-897b-4dee2d2034ec.png)

![starry_16](https://cloud.githubusercontent.com/assets/352383/12124892/493ac940-b3a5-11e5-954b-03fda2da42f2.png)

![scream_19](https://cloud.githubusercontent.com/assets/352383/12124896/579f80e8-b3a5-11e5-8c75-cac890cce3af.png)

![scream_16](https://cloud.githubusercontent.com/assets/352383/12124904/62871228-b3a5-11e5-8097-11cd7e007432.png)

**Comment by djdjoko** [comment]
It seems like the 16layer works better for faces and 19layer for landscape.

**Comment by djdjoko** [comment]
Hi,
I downloaded the vgg_face_caffe.tar.gz from the website you specified unpacked them and run the model VGG_FACE.caffemodel and proto text VGG_FACE_deploy.prototxt but get an almost blank output image:

th neural_style.lua -proto_file VGG_FACE_deploy.prototxt -model_file VGG_FACE.caffemodel  -gpu 0 -backend cudnn

I see your model and prototext file you are running are named differently in your previous post and I am wondering if I am pointing to the wrong model files:

th neural_style.lua -proto_file VGG_ILSVRC_16_layers_deploy.prototxt -model_file VGG_ILSVRC_16_layers.caffemodel  -gpu 0 -backend cudnn

Do you have a suggestion what could be the problem?

**Comment by 3DTOPO** [comment]
You need to specify paths to the model and photo file on your system. If that doesn't help; what specific errors are you getting?

**Comment by djdjoko** [comment]
I have specified the paths correctly as I do not get any errors. The code runs but the image is just blank (it works for VGG_19 though). It seems like it does not converge. I see that the model name you run are different to what I downloaded. Not sure if they have updated the model on the download site or if I am running the wrong files.

**Comment by 3DTOPO** [comment]
My Apologies; I downloaded too many models that day. The examples above are created from the ImageNet ILSVRC-2014 16-layer model. Apparently I got the names confused because the face model is 16-layers as well.

**Comment by djdjoko** [comment]
Ok:) Do you have a link handy where you downloaded it? Also did you make the model work from the link you previously submitted:

http://www.robots.ox.ac.uk/~vgg/software/vgg_face/

**Comment by 3DTOPO** [comment]
They are here (it is the source of the default 19-layer model): http://www.robots.ox.ac.uk/%7Evgg/research/very_deep/

Apparently not - I'll take a look at the face model again, sounds like it doesn't work well though.

**Comment by djdjoko** [comment]
Thank you! Seems to work now

**Comment by austingg** [comment]
@3DTOPO  have you make face model work eventually?  I tried vgg_face model, and could not get good result. Maybe the training data is too different with ILSVRC's
