### ISSUE TITLE
OpenCL usage with NIN Model not work

### ISSUE THREAD

**Issue by mickeyinfoshan** [jcjohnson/neural-style#114]
My computer is a mac. I've installed cltorch and clnn. I've downloaded NIN model. When I tried `h neural_style.lua -style_image examples/inputs/picasso_selfport1907.jpg -content_image examples/inputs/brad_pitt.jpg -output_image profile.png -model_file models/nin_imagenet_conv.caffemodel -proto_file models/train_val.prototxt -gpu 0 -backend clnn -num_iterations 1000 -seed 123 -content_layers relu0,relu3,relu7,relu12 -style_layers relu0,relu3,relu7,relu12 -content_weight 10 -style_weight 1000 -image_size 512 -optimizer adam` as `readme`, i got an error:
`Users/tianchishao/torch/install/bin/luajit: ...s/tianchishao/torch/install/share/lua/5.1/trepl/init.lua:383: ...s/tianchishao/torch/install/share/lua/5.1/trepl/init.lua:383: ...tianchishao/torch/install/share/lua/5.1/cltorch/init.lua:19: cannot load '/Users/tianchishao/torch/install/lib/lua/5.1/libcltorch.so'
stack traceback:
    [C]: in function 'error'
    ...s/tianchishao/torch/install/share/lua/5.1/trepl/init.lua:383: in function 'require'
    neural_style.lua:55: in function 'main'
    neural_style.lua:499: in main chunk
    [C]: in function 'dofile'
    ...shao/torch/install/lib/luarocks/rocks/trepl/scm-1/bin/th:145: in main chunk
    [C]: at 0x010655abc0`

What's wrong? How can I fix it?

**Comment by jcjohnson** [comment]
Looks like a problem with the `clnn` import. If you launch an interactive torch session with the `th` command, can you successfully import `cltorch` and `clnn`?
