### ISSUE TITLE
Is there a way to run this algorithm without running out of memory for larger image sizes?

### ISSUE THREAD

**Issue by zfrenchee** [jcjohnson/neural-style#122]
I have a GTX 960. I think I have 4GB of memory on there. I can't make images much larger than 500px. Is that normal, and if so, is that immutable?

**Comment by jcjohnson** [comment]
That sounds about right. VGG-19 is very memory-hungry.

To reduce memory usage you can try running with the cudnn backend and try using Adam rather than L-BFGS; but even with those tricks you still won't be getting HD images with 4GB of GPU memory.

**Comment by zfrenchee** [comment]
How large of an image could you get with something like a Titan? Is it more or less linear, i.e. 4x the memory -> 4x the pixels in the output image, meaning 2x the sidelength?

**Comment by jcjohnson** [comment]
I can get around 2000px using a Titan X with 12GB, but it's pretty slow.

**Comment by zfrenchee** [comment]
Hahaha. How slow?

**Comment by austingg** [comment]
and you can try some smaller network ,such as VGG-16

**Comment by 3DTOPO** [comment]
I suspect that won't get anywhere near 2000px for a square image on a TiX though. The area is what seems to matter. Also, the scale (and number of) style images makes difference too. I wish there was a clear way to calculate the memory usage before running...

VGG-16 makes little practical difference in my experience.

**Comment by zfrenchee** [comment]
As someone with no experience in GPU programming, I don't really understand why this should be slow -- it seems like you should be able to do a lot of stuff sequentially and dump stuff on ram in the meantime. 
Oh well.

**Comment by 3DTOPO** [comment]
That is because it isn't a shader or similar. IIRC correctly the VGG model packs around 650 million emulated neurons.

The computations are done in parallel - otherwise there would be no benefit running on a GPU. ;)

**Comment by zfrenchee** [comment]
Well you could hypothetically do it in parallel batches, maybe with a stride or something. Something smoother than taking a big image, chopping it into sections, and then running the algorithm on each section, and stitching them back together.

**Comment by 3DTOPO** [comment]
That doesn't make it any less computationally intensive (in fact the opposite is true).
