### ISSUE TITLE
neural-style running multi-thread on one cpu but not on another

### ISSUE THREAD

**Issue by 1SittingDuck** [jcjohnson/neural-style#124]
Hi JC

Firstly thanks for publishing your work with Neural Algortithm in LUA. I have learned a great deal from following your guides and advice. The speed from CUDNN is amazing for testing variouse parameters, however from having GPUs only with 2gb memory and wanting to have larger than 512 pixel images I have been running neural-style in cpu mode with 1024-1600 pixel images.

On one server with a 3820 CPU and 64gb memory I can start four 1024pixel runs which use approx 15-16gb memory. System load runs around 4 which indicates luajit is only utilizing one core per process. Result are that it takes days to complete an image.

On a second server with a 4820K CPU and 64gb memory I can start 2 1024pixel runs which use approx 30gb memory each luajit process and system load is around 8 indicating it is utilizing all 8 cores. Results are that it only takes a few hours for each image.
Both servers are running the same Ubuntu 14.04 with latest patches and identical torch cunn neural-style etc.

I would really like to get the system with the 3820 CPU to utilize more memory and processors per luajit process. Is there some inherent difference in these two processors which limits the 3820 thay you may be aware of? From Intel specs and benchmarks these two processors should be very close in performance, but my experience has shown quite the contrary when running neural-style and luajit. 

Any ideas where I can look to uncover the reasons or perhaps even configure the 3820 system to utilzie the same speed and resources that I'm getting from the 4820K would be greatly appreciated.

**Comment by jcjohnson** [comment]
neural-style depends on torch7 for multithreaded CPU speedup, which in turn depends on a BLAS implementation (usually OpenBLAS). My guess is that one one machine you have torch and BLAS properly configured to use multiple cores, and on the other machine your either your torch install is not properly linked to your BLAS install, or that your BLAS install was configured to use only a single core.

I've never had to debug this myself, but some starting points might be this [this GitHub issue](https://github.com/torch/torch7/issues/52) concerning torch7 installation and OpenBLAS and [the OpenBLAS documentation](http://www.openblas.net/).

**Comment by 1SittingDuck** [comment]
Many thanks! you pinpointed the issue correctly. I had installed torch7 on the non-multi-threading server sometime in September 2015. 
So I just reinstalled torch7 again on that server and voila! it is mutli-threading.
yippeee!

**Comment by jcjohnson** [comment]
Glad you figured it out!
