### ISSUE TITLE
<optim.lbfgs> 	creating recyclable direction/step/history buffers 

### ISSUE THREAD

**Issue by Meir770** [jcjohnson/neural-style#125]
Hello. I am trying to  run a command and when It starts "optimization with L-BFGS", doesn't continue.

LOL~th neural_style.lua -gpu -1 -style_image /Users/Meir/neural-style/examples/inputs/starry_night.jpg -content_image /Users/Meir/neural-style/examples/inputs/brad_pitt.jpg
[libprotobuf WARNING google/protobuf/io/coded_stream.cc:537] Reading dangerously large protocol message.  If the message turns out to be larger than 1073741824 bytes, parsing will be halted for security reasons.  To increase the limit (or to disable these warnings), see CodedInputStream::SetTotalBytesLimit() in google/protobuf/io/coded_stream.h.
[libprotobuf WARNING google/protobuf/io/coded_stream.cc:78] The total number of bytes read was 574671192
Successfully loaded models/VGG_ILSVRC_19_layers.caffemodel
conv1_1: 64 3 3 3
conv1_2: 64 64 3 3
conv2_1: 128 64 3 3
conv2_2: 128 128 3 3
conv3_1: 256 128 3 3
conv3_2: 256 256 3 3
conv3_3: 256 256 3 3
conv3_4: 256 256 3 3
conv4_1: 512 256 3 3
conv4_2: 512 512 3 3
conv4_3: 512 512 3 3
conv4_4: 512 512 3 3
conv5_1: 512 512 3 3
conv5_2: 512 512 3 3
conv5_3: 512 512 3 3
conv5_4: 512 512 3 3
fc6: 1 1 25088 4096
fc7: 1 1 4096 4096
fc8: 1 1 4096 1000
Setting up style layer  	2	:	relu1_1
Setting up style layer  	7	:	relu2_1
Setting up style layer  	12	:	relu3_1
Setting up style layer  	21	:	relu4_1
Setting up content layer	23	:	relu4_2
Setting up style layer  	30	:	relu5_1
WARNING: Skipping content loss
Running optimization with L-BFGS
<optim.lbfgs> 	creating recyclable direction/step/history buffers

....and not response. What am I doing wrong?

P.S. OS X

**Comment by jcjohnson** [comment]
By default it only prints every 50 iterations. Since you are running on CPU it might take a while to complete 50 iterations and it looks like it's hanging. Try adding the flag `-print_iter 1` to print progress every iteration.

**Comment by Meir770** [comment]
Thanks
