### ISSUE TITLE
Pikazo App..Does it use neural style?

### ISSUE THREAD

**Issue by meric** [jcjohnson/neural-style#126]
I saw this on Hacker News (https://news.ycombinator.com/item?id=10993919, http://www.pikazoapp.com)

Is it your app, @jcjohnson? Otherwise if it does use the same algorithm, kind of strange it doesn't mention this repository at all.

**Comment by joker-b** [comment]
If you follow the links to the first mention of deepart.io, this repo is mentioned.

I leave it to reddit and the marketing dept to decide if images are art.

**Comment by jcjohnson** [comment]
I honestly have no idea if Pikazo uses my code; the results don't really look like my results, but they may have also tweaked the settings to try and get it to converge faster.

I think deepart.io was at one point using my code, but now that they have the original algorithm creators on-board they may actually be using the original implementation from the paper.
