### ISSUE TITLE
new default parameters perform poorly on saturated images

### ISSUE THREAD

**Issue by bobbens** [jcjohnson/neural-style#13]
Just want to point out that the hyperparameters before 11f8313b46f0bcf50af1f6883ff2a8c601f3ba5c were working much better for me. Now with the newer ones it tends to have issues on images with saturated areas (either all black or all white). I do understand that this is a pretty image dependent, but just wanted to give some feedback until some sort of "gold standard" of hyperparameters can be found. Kudos for the great work.

**Comment by jcjohnson** [comment]
Thank for the feedback. You're right that they are pretty image dependent; the new defaults worked better on all the images I tried, but then again I didn't try anything with heavily saturated areas.
