### ISSUE TITLE
Hangs at "creating recyclable direction/step/history buffers"

### ISSUE THREAD

**Issue by gonchs** [jcjohnson/neural-style#136]
Running this with 20 cores / 64GB RAM in cpu mode:

ubuntu@deep-style:~/neural-style$ th neural_style.lua -gpu -1 -print_iter -1 -backend cudnn -cudnn_autotune
[libprotobuf WARNING google/protobuf/io/coded_stream.cc:505] Reading dangerously large protocol message.  If the message turns out to be larger than 1073741824 bytes, parsing will be halted for security reasons.  To increase the limit (or to disable these warnings), see CodedInputStream::SetTotalBytesLimit() in google/protobuf/io/coded_stream.h.
[libprotobuf WARNING google/protobuf/io/coded_stream.cc:78] The total number of bytes read was 574671192
Successfully loaded models/VGG_ILSVRC_19_layers.caffemodel
conv1_1: 64 3 3 3
conv1_2: 64 64 3 3
conv2_1: 128 64 3 3
conv2_2: 128 128 3 3
conv3_1: 256 128 3 3
conv3_2: 256 256 3 3
conv3_3: 256 256 3 3
conv3_4: 256 256 3 3
conv4_1: 512 256 3 3
conv4_2: 512 512 3 3
conv4_3: 512 512 3 3
conv4_4: 512 512 3 3
conv5_1: 512 512 3 3
conv5_2: 512 512 3 3
conv5_3: 512 512 3 3
conv5_4: 512 512 3 3
fc6: 1 1 25088 4096
fc7: 1 1 4096 4096
fc8: 1 1 4096 1000
Setting up style layer  	2	:	relu1_1
Setting up style layer  	7	:	relu2_1
Setting up style layer  	12	:	relu3_1
Setting up style layer  	21	:	relu4_1
Setting up content layer	23	:	relu4_2
Setting up style layer  	30	:	relu5_1
WARNING: Skipping content loss
Running optimization with L-BFGS
<optim.lbfgs> 	creating recyclable direction/step/history buffers

Looking at htop, it still seems to be working but there has been no further output for about 30 minutes.

**Comment by bododge** [comment]
try setting -print_iter to 1 instead of -1.  I don't know if negative numbers in -print_iter will disable or not, but try using a low positive value like 1 or 2. Alternatively try setting -save_iter to 1 or 2 and see if you new files are being created. I think it will take more than 30 minutes to reach the first default -print_iter and far more than 30 minutes to finish the 1000 iters.

**Comment by gonchs** [comment]
Thanks, this fixed it. I didn't notice -print_iter was **minus** 1. It's now printing an iteration every 10 seconds or so.

**Comment by htoyryla** [comment]
Sergey Goncharov <notifications@github.com> kirjoitti 25.2.2016 kello 20.26:

> Thanks, this fixed it. I didn't notice -print_iter was minus 1. It's now printing an iteration every 10 seconds or so.
> 
Looks like there is an error in INSTALL.md:

"You should now be able to run neural-style in CPU mode like this:

th neural_style.lua -gpu -1 -print_iter -1"
br
Hannu

**Comment by jcjohnson** [comment]
Wow good catch! I think that typo tripped up many people ... sorry!

**Comment by syk0saje** [comment]
I also hit this just now. There's still no `-print_iter -1` next to the `-gpu -1` instances in the README. Maybe those should be added?

**Comment by htoyryla** [comment]
> I also hit this just now. There's still no -print_iter -1 next to the -gpu -1 instances in the README. Maybe those should be added?
> 

No. Print_iter -1 was a typo in INSTALL.md which prevented iteration output from being displayed.
