### ISSUE TITLE
Why do I get this? "WARNING: Skipping content loss"

### ISSUE THREAD

**Issue by bnsh** [jcjohnson/neural-style#137]
Hi.. It's not really a "issue", just a question... But, I didn't know where else to ask this:

But, when I run it like so:

`th neural_style.lua -backend cudnn -cudnn_autotune -print_iter 100 -save_iter 1 -num_iterations 1000 -image_size 512 -style_image ./examples/inputs/starry_night.jpg -content_image examples/inputs/hoovertowernight.jpg -output_image /tmp/hoovertowernight-starry.jpg`

I get this warning:

`WARNING: Skipping content loss	`

Is that to be expected?

Thanks!
Binesh

**Comment by jcjohnson** [comment]
That's expected at the beginning when the network is being set up; if you see that message on every iteration then something has gone terribly wrong.
