### ISSUE TITLE
Ends abruptly with the message: Killed

### ISSUE THREAD

**Issue by chirag64** [jcjohnson/neural-style#15]
Hi,

I'm trying to run this on Arch Linux without a GPU and 8GB RAM.

Earlier, I got the exact same errors mentioned in #14 but I followed the steps mentioned and those problems were solved.

But now, I'm getting this error where the script tries to run until the second last line, waits for a few seconds (probably trying to process) and then ends abruptly without any detailed message. Just the word 'Killed'.

```
th neural_style.lua -style_image examples/inputs/starry_night.jpg -content_image examples/inputs/brad_pitt.jpg -gpu -1 -output_image file.png [libprotobuf WARNING google/protobuf/io/coded_stream.cc:537] Reading dangerously large protocol message.  If the message turns out to be larger than 1073741824 bytes, parsing will be halted for security reasons.  To increase the limit (or to disable these warnings), see CodedInputStream::SetTotalBytesLimit() in google/protobuf/io/coded_stream.h.
[libprotobuf WARNING google/protobuf/io/coded_stream.cc:78] The total number of bytes read was 574671192
Successfully loaded models/VGG_ILSVRC_19_layers.caffemodel
conv1_1: 64 3 3 3
conv1_2: 64 64 3 3
conv2_1: 128 64 3 3
conv2_2: 128 128 3 3
conv3_1: 256 128 3 3
conv3_2: 256 256 3 3
conv3_3: 256 256 3 3
conv3_4: 256 256 3 3
conv4_1: 512 256 3 3
conv4_2: 512 512 3 3
conv4_3: 512 512 3 3
conv4_4: 512 512 3 3
conv5_1: 512 512 3 3
conv5_2: 512 512 3 3
conv5_3: 512 512 3 3
conv5_4: 512 512 3 3
fc6: 1 1 25088 4096
fc7: 1 1 4096 4096
fc8: 1 1 4096 1000
WARNING: Skipping content loss
Killed
```

**Comment by jcjohnson** [comment]
Hmm, maybe you are running out of memory? Try watching top while it runs.

**Comment by SirSpunky** [comment]
I also get this error when trying to start a 512 sized network on the CPU, in my case on a virtual machine Ubuntu with about 5 GB dedicated RAM. I also think it's a memory issue, as 256 is the largest resolution I've been able to use without artifacts. Maybe the CPU cannot utilize memory as efficiently as the GPU in when it comes to this, unfortunately.

Try adding "-image_size 256" to the parameters to run a smaller network. (Maybe this should even be the default value, Justin?)

**Comment by chirag64** [comment]
It does seem like a memory issue. Thanks, @SirSpunky, that parameter seems to have fixed the problem. I wish there was a more descriptive error, but I guess that is part of the library.

Thanks, @jcjohnson for making this. :)

**Comment by Groxot** [comment]
I have 4Gb memory but have the same error and can use only -image_size 256
How fix it?
