### ISSUE TITLE
difference between local and deepart.io

### ISSUE THREAD

**Issue by hosok2** [jcjohnson/neural-style#157]
Hello,

I'm trying to duplicate the result that I got from deepart.io with the same contents and style images in my local machine. I tried lbfgs and adam with other args and also played with style_scale little bit. However the result from deepart.io looks much better. Does anyone know if there is any other process done on the website? or any way to improve the result?

Thanks!

![insideout_4_modeltest_01_ 1](https://cloud.githubusercontent.com/assets/1479271/13549347/fbe09976-e2b7-11e5-9c51-4d5b0b14c0c4.png)
local test

![](https://deepart-io.s3.amazonaws.com/results/1c7dd2e03628ea21-359255.png)
from http://deepart.io/result/359255/

**Comment by joker-b** [comment]
I would first try increasing the style_weight. Are both output images the
same size?

**Comment by jcjohnson** [comment]
Looks to me like the deepart.io one is using a larger style scale.

I suspect that deepart.io also has some extra tricks not present in neural-style, especially since they are able to produce high-res 1300 x 1300 in 10 minutes and ultra-high res 3000 x 3000 in a day. AFAIK they have not publicly disclosed exactly how their process works.

**Comment by hosok2** [comment]
joker-b: Both images are not the same size, but that was also the case on deepart.io. I also tried different style_weight which seems to help little bit but not exactly same as one from deepart.io.

jcjohnson: Thanks for the info. It's good to know there could be some other tricks that they didn't disclose.

**Comment by sheerun** [comment]
@hosok2 Who are you representing? I can consult you to have exactly the same results (except high res quality). I can also setup service for generating them. Please ping me on sheerun@sher.pl with an offer.

**Comment by joker-b** [comment]
fwiw, I spoke to Leon Gatys for about two minutes at the recent GrayArea "Deep Dreaming" event -- they use GPUs like anyone else, and are memory-bound: they are using an IBM cloud service which provides more GPU memory than does AWS.

**Comment by sheerun** [comment]
If someone is interested in parameters for neural style that reproduce deepart, please visit:
https://buy.sheerun.net/products/deepart-io-neural-style-parameters

**Comment by sheerun** [comment]
Here are parameters I've used:

```
th neural_style.lua \
-style_image $(pwd)/style.jpg \
-content_image $(pwd)/content.jpg \
-output_image $(pwd)/output.jpg \
-gpu 0 \
-init image \
-content_weight 5 \
-style_weight 1000 \
-style_scale 1 \
-image_size 500 \
-num_iterations 1000 \
-cudnn_autotune \
-backend cudnn \
-tv_weight 0.001
```

Please like this comment if they work for you, thank you
