### ISSUE TITLE
Noise

### ISSUE THREAD

**Issue by techmago** [jcjohnson/neural-style#17]
Hey, how i get rid of this weird noise messing my tests?
![out_200](https://cloud.githubusercontent.com/assets/7603588/9690551/620e4606-5313-11e5-9d63-26b9594626ba.png)

[code]
root@techmago-VirtualBox:~/neural-style# th neural_style.lua -image_size 300 -style_image A4.jpg -content_image B1.jpg -gpu -1 -num_iterations 1000 -save_iter 50 -style_weight 90
[libprotobuf WARNING google/protobuf/io/coded_stream.cc:505] Reading dangerously large protocol message.  If the message turns out to be larger than 1073741824 bytes, parsing will be halted for security reasons.  To increase the limit (or to disable these warnings), see CodedInputStream::SetTotalBytesLimit() in google/protobuf/io/coded_stream.h.
[libprotobuf WARNING google/protobuf/io/coded_stream.cc:78] The total number of bytes read was 574671192
Successfully loaded models/VGG_ILSVRC_19_layers.caffemodel
[/code]

**Comment by jcjohnson** [comment]
Upgrade your torch image package: `luarocks install image`.

**Comment by techmago** [comment]
Wow, just that?
So much love for you!
