### ISSUE TITLE
Is it possible to use this project for production?

### ISSUE THREAD

**Issue by vtkngoc510** [jcjohnson/neural-style#176]
Hi Justin,
I want to make a mobile app that allows user to create artistic photo with this project. I wonder if I can use our project for a production app.
Thank you very much.

**Comment by jcjohnson** [comment]
It's MIT licensed, so go ahead. Making it scale to production seems like a hard problem to me, but you are welcome to try.

**Comment by vtkngoc510** [comment]
Thank you very much :+1:

**Comment by 0wnrepo** [comment]
It's not feasible at the current speed. Did you even try to test it ?
