### ISSUE TITLE
saturation artifacts

### ISSUE THREAD

**Issue by soumith** [jcjohnson/neural-style#18]
I'm getting these weird saturation artifacts, any chance you've seen the same? I played around with the tv weight and other knobs to try fix it, but no luck.

![out](https://cloud.githubusercontent.com/assets/1310570/9694690/fa8e8782-5328-11e5-9c91-11f7b215ad19.png)

**Comment by jcjohnson** [comment]
That seems to happen when using an older version of the image package; updating it should fix the problem: `luarocks install image`

**Comment by soumith** [comment]
ah, cool. thanks.

**Comment by jcjohnson** [comment]
Lots of people are having this problem so I'll add it to the README.

**Comment by randomrandom** [comment]
Hi, I've ran into the same problem when creating images below 512px. I've tried `luarocks install image`, however it didn't seem to change anything.

Here's the sample (size: 300x400):
![image](https://cloud.githubusercontent.com/assets/1579822/13745924/5a2ccc64-e9f9-11e5-8142-b7a297cac304.png)

Any ideas what I might be doing wrong? I can provide more parameters if necessary. This image is
