### ISSUE TITLE
Scale up an image maintaining the appearance

### ISSUE THREAD

**Issue by kineticsystem** [jcjohnson/neural-style#180]
I've only recently started using this application which is quite amazing but I don't yet fully understand. I've now run into what I think is a common issue.

I have an input image that is quite big e.g. 1872x2808 and a style image which is 612x612.
Using GPU I can generate a 341x512 image decently fast using a style scale 0.8. 

Now... I like the result and I would like to scale up the image to 866x1300. I have 32GB of RAM and I can let it run with CPU all night. Unfortunately the bigger image looks quite different from the small one. I tried to play with the style scale but I cannot get the same appearance.

Can anybody suggest me how to properly use the parameters so I can generate a fast small preview using GPU and then later a bigger image using CPU, while maintaining the preview appearance?

In exchange for the favor I attach the steps I use to install this software on Xubuntu 15.10 and Cuda 7.5. Maybe there are few things inside that may be useful for you guys.

Kind Regards,

Giovanni

---

HOW TO INSTALL NEURAL-STYLE SOFTWARE

DUMMY PLUG

To start Xubuntu with the proprietary NVIDIA driver without a monitor you need to build a dummy plug for the graphic card to trick the OS into thinking that there is a VGA monitor attached.
https://rumorscity.com/2013/12/06/how-to-create-dummy-plugs-for-your-graphics-cards/
I followed the instructions using 3 x 120 ohms restistors.

INSTALL NVIDIA DRIVERS

In Xubuntu start the Software Updater and press the button "Settings...".
Select the "Additional Drivers" tab and once a list of driver is displayed select and install
"NVIDIA binary driver - version 352.63 from nvidia-352 (propietary,tested)"

Type "nvidia-smi" to check if the driver is installed. 

At this stage it is important to reboot.

INSTALL NVIDIA CUDA Toolkit 7.5

Download the latest deb package for Ubuntu here
https://developer.nvidia.com/cuda-downloads

Download the file
cuda-repo-ubuntu1504-7-5-local_7.5-18_amd64.deb

Run
sudo dpkg -i cuda-repo-ubuntu1504-7-5-local_7.5-18_amd64.deb
sudo apt-get update
sudo apt-get install cuda

As part of the CUDA environment, you should add the following in the .bashrc file of your home folder.

export CUDA_HOME=/usr/local/cuda-7.5 
export LD_LIBRARY_PATH=${CUDA_HOME}/lib64 

PATH=${CUDA_HOME}/bin:${PATH} 
export PATH 

COMPILER SETTINGS

Add the following lines to your .bashrc

export CC=gcc-4.9
export PATH=$PATH:/usr/local/cuda-7.5/bin
export LD_LIBRARY_PATH=:/usr/local/cuda-7.5/lib64
export PATH=$PATH:/usr/local/cuda-7.5/targets/x86_64-linux/include
export LD_LIBRARY_PATH=:/usr/local/cuda-7.5/targets/x86_64-linux/lib
export PATH=$PATH:/usr/lib/gcc/x86_64-linux-gnu/4.9

At this stage it is important to reboot otherwise Torch7 won't compile properly.

INSTALL TORCH7

Run the following commands

cd ~/
curl -s https://raw.githubusercontent.com/torch/ezinstall/master/install-deps | bash
git clone https://github.com/torch/distro.git ~/torch --recursive
cd ~/torch; ./install.sh
source ~/.bashrc

INSTALL LOADCAFFE

sudo apt-get install libprotobuf-dev protobuf-compiler
luarocks install loadcaffe

INSTALL NEURAL-STYLE

cd ~/
git clone https://github.com/jcjohnson/neural-style.git
cd neural-style
sh models/download_models.sh

Test the installation with the following command

th neural_style.lua -gpu -1 -print_iter 1

INSTALL CUDA BACKEND FOR TORCH

luarocks install cutorch
luarocks install cunn

You can check that the installation worked by running the following:

th -e "require 'cutorch'; require 'cunn'; print(cutorch)"

INSTALL CUDNN

cuDNN is a library from NVIDIA that efficiently implements many of the operations (like convolutions and pooling) that are commonly used in deep learning. Register as a developer and download the cuDNN file from here

https://developer.nvidia.com/cudnn

Then run

tar -xzvf cudnn-7.0-linux-x64-v4.0-prod.tgz
sudo cp cuda/lib64/libcudnn\* /usr/local/cuda-7.5/lib64/
sudo cp cuda/include/cudnn.h /usr/local/cuda-7.5/include/
luarocks install cudnn

**Comment by xenon2** [comment]
It's a wild guess (im playing with this only 2 days), maybe try to upscale style image to match % ratio of output.

**Comment by kineticsystem** [comment]
Isn't this what the scale parameter is supposed to do? I will try to play a bit more with the scale parameter and also to physically scale up the style image. Thanks, Giovanni

**Comment by htoyryla** [comment]
kineticsystem <notifications@github.com> kirjoitti 16.3.2016 kello 16.28:

> Isn't this what the scale parameter is supposed to do?
> 
Or maybe not. It seems to me that the original purpose has been to affect in which scale the style features appear in the output image.
> I will try to play a bit more with the scale parameter and also to physically scale up the style image. Thanks, Giovann
> 
The original size of the style image should not matter. Neural-style resizes the style image to  image_size * style_scale. 

BTW, this also appears to have the effect that memory usage increases together with style_scale.

Anyway, the question of how to obtain similar results when changing image size is an interesting problem. The README file suggests to try different content and style weights.  

Hannu

**Comment by htoyryla** [comment]
Just some random thoughts about this that have crosses my mind as I, too, have made some tests but not really been able to produce a similar look at double scale. Now the core of neural-style is the convolutional neural network which has been trained to recognize features in images. The network does this by convolutions, in essence sliding a window of fixed size over each layer in the network. 

Now when the image size is doubled, but the kernel window remains fixed, it will see a smaller part of the image when looking for stylistical features. This does not seem to matter so much with regard to content, but it might affect style, kind of bringing about a tendency to concentrate on smaller details in the image.

Now changing the kernel size is not easy. We might generate a similar network with larger kernels but then we would lose the training and the network would be useless. Training a network from scratch would be a large task, taking into account that the larger size of training images require more memory and computing power.

Still, I wonder if deepart.io have done precisely this. The fact that they are offering a few fixed image sizes would match with the idea of using neural networks optimized for certain image sizes.

In essence, I am wondering whether it would at all be possible, using a neural network with fixed kernel size, to achieve consistent results across a range of image sizes by merely changing the scales and weights?
