### ISSUE TITLE
loadcaffe.load causing luajit: C++ exception

### ISSUE THREAD

**Issue by rrama** [jcjohnson/neural-style#182]
When running the command
th ~/neural-style/neural_style.lua -gpu -1 -print_iter 1 -style_image ~/towerfall.jpg -content_image ~/tom.jpg -output_image ~/out.png

I get the following:

[libprotobuf WARNING google/protobuf/io/coded_stream.cc:505] Reading dangerously large protocol message.  If the message turns out to be larger than 1073741824 bytes, parsing will be halted for security reasons.  To increase the limit (or to disable these warnings), see CodedInputStream::SetTotalBytesLimit() in google/protobuf/io/coded_stream.h.
[libprotobuf WARNING google/protobuf/io/coded_stream.cc:78] The total number of bytes read was 574671192
Successfully loaded models/VGG_ILSVRC_19_layers.caffemodel
/home/ubuntu/torch/install/bin/luajit: C++ exception

I have narrowed it down to the line 73:
local cnn = loadcaffe.load(params.proto_file, params.model_file, loadcaffe_backend):float()

Does anyone have any advice on how I can try to further determine the problem?

**Comment by rrama** [comment]
Turned out that the process wasn't getting enough memory.

I realised that when I ran with
-model_file ~/neural-style/models/vgg_normalised.caffemodel -optimizer adam
it got further, sorry if I wasted anyone's time.

**Comment by caroline96x** [comment]
I'm having the same problem now, I tried adding 
-model_file ~/neural-style/models/vgg_normalised.caffemodel -optimizer adam,
but it still didn't work out.
Do you know what's fixed by the code above?
thx a lot
