### ISSUE TITLE
no outputs?

### ISSUE THREAD

**Issue by dribnet** [jcjohnson/neural-style#2]
Has anyone reported this working in the wild yet? For me, everything runs but loss is stuck and all outputs are just black images.

```bash
th neural_style.lua -style_image examples/inputs/picasso_selfport1907.jpg -content_image examples/inputs/brad_pitt.jpg -image_size 200
[libprotobuf WARNING google/protobuf/io/coded_stream.cc:537] Reading dangerously large protocol message.  If the message turns out to
 be larger than 1073741824 bytes, parsing will be halted for security reasons.  To increase the limit (or to disable these warnings),
 see CodedInputStream::SetTotalBytesLimit() in google/protobuf/io/coded_stream.h.
[libprotobuf WARNING google/protobuf/io/coded_stream.cc:78] The total number of bytes read was 574671192
Successfully loaded models/VGG_ILSVRC_19_layers.caffemodel
conv1_1: 64 3 3 3
conv1_2: 64 64 3 3
conv2_1: 128 64 3 3
conv2_2: 128 128 3 3
conv3_1: 256 128 3 3
conv3_2: 256 256 3 3
conv3_3: 256 256 3 3
conv3_4: 256 256 3 3
conv4_1: 512 256 3 3
conv4_2: 512 512 3 3
conv4_3: 512 512 3 3
conv4_4: 512 512 3 3
conv5_1: 512 512 3 3
conv5_2: 512 512 3 3
conv5_3: 512 512 3 3
conv5_4: 512 512 3 3
fc6: 1 1 25088 4096
fc7: 1 1 4096 4096
fc8: 1 1 4096 1000
Iteration 50 / 1000
  Content 1 loss: 112580.012500
  Style 1 loss: 662369.445801
  Style 2 loss: 10171917.968750
  Style 3 loss: 3723512.109375
  Style 4 loss: 7359701.250000
  Style 5 loss: 14420980.000000
Iteration 100 / 1000
  Content 1 loss: 112580.012500
  Style 1 loss: 662369.445801
  Style 2 loss: 10171917.968750
  Style 3 loss: 3723512.109375
  Style 4 loss: 7359701.250000
  Style 5 loss: 14420980.000000
...
```
![out](https://cloud.githubusercontent.com/assets/945979/9600558/8d1579b6-5050-11e5-9e46-9c8a778a8ea5.png)

**Comment by jcjohnson** [comment]
If you get a black output like this, then try reducing the learning rate, the style weight, or the content weight.

**Comment by dribnet** [comment]
Thanks - lowered all 3 by and order of magnitude and now something is happening. Might suggest adding a line to the README that gives a known working command line for one of the example images.

**Comment by dribnet** [comment]
Just as a footnote: I wasn't able to use this because your memory requirements - and when I reduce the image size to 200 I get corrupt outputs (I've seen this behavior in other implementations as well when small image sizes don't process correctly). Not sure why your memory requirements would be higher than the other implementation I tried or if that's a solvable problem.
