### ISSUE TITLE
Improve Setup Documentation

### ISSUE THREAD

**Issue by dodekeract** [jcjohnson/neural-style#20]
I want to setup this, but I honestly have no idea what to do. The README does not provide enough information on that. For example: It needs torch7 as a dependency, but how can I setup that?

**Comment by ZuzooVn** [comment]
Here ya go : http://torch.ch/docs/getting-started.html#_

**Comment by jcjohnson** [comment]
I added an installation guide:

https://github.com/jcjohnson/neural-style/blob/master/INSTALL.md
