### ISSUE TITLE
Issue installing cuDNN

### ISSUE THREAD

**Issue by harrydwilde** [jcjohnson/neural-style#201]
I have cuda 7.5 and am trying to install cuDNN 5, whereas the tutorial does only mention 4. However I am sure I've seen other people using cuda 7.5 which means surely they too use cudnn 5. I have done the following
sudo cp cuda/lib64/libcudnn* /usr/local/cuda-7.5/lib64/
sudo cp cuda/include/cudnn.h /usr/local/cuda-7.5/include/

**and it installs ok**
harry@harry:~/neural-style$ luarocks install cudnn
Installing https://raw.githubusercontent.com/torch/rocks/master/cudnn-scm-1.rockspec...
Using https://raw.githubusercontent.com/torch/rocks/master/cudnn-scm-1.rockspec... switching to 'build' mode
Cloning into 'cudnn.torch'...
remote: Counting objects: 44, done.
remote: Compressing objects: 100% (40/40), done.
remote: Total 44 (delta 13), reused 22 (delta 2), pack-reused 0
Receiving objects: 100% (44/44), 44.70 KiB | 0 bytes/s, done.
Resolving deltas: 100% (13/13), done.
Checking connectivity... done.
cmake -E make_directory build && cd build && cmake .. -DCMAKE_BUILD_TYPE=Release -DCMAKE_PREFIX_PATH="/home/harry/torch/install/bin/.." -DCMAKE_INSTALL_PREFIX="/home/harry/torch/install/lib/luarocks/rocks/cudnn/scm-1" && make

-- The C compiler identification is GNU 4.9.3
-- The CXX compiler identification is GNU 4.9.3
-- Check for working C compiler: /usr/bin/cc
-- Check for working C compiler: /usr/bin/cc -- works
-- Detecting C compiler ABI info
-- Detecting C compiler ABI info - done
-- Detecting C compile features
-- Detecting C compile features - done
-- Check for working CXX compiler: /usr/bin/c++
-- Check for working CXX compiler: /usr/bin/c++ -- works
-- Detecting CXX compiler ABI info
-- Detecting CXX compiler ABI info - done
-- Detecting CXX compile features
-- Detecting CXX compile features - done
-- Found Torch7 in /home/harry/torch/install
-- Found CUDA: /usr/local/cuda (found suitable version "7.5", minimum required is "7.0") 
-- Configuring done
-- Generating done
-- Build files have been written to: /tmp/luarocks_cudnn-scm-1-1243/cudnn.torch/build
cd build && make install
Install the project...
-- Install configuration: "Release"
-- Installing: /home/harry/torch/install/lib/luarocks/rocks/cudnn/scm-1/lua/cudnn/Tanh.lua
-- Installing: /home/harry/torch/install/lib/luarocks/rocks/cudnn/scm-1/lua/cudnn/Sigmoid.lua
-- Installing: /home/harry/torch/install/lib/luarocks/rocks/cudnn/scm-1/lua/cudnn/convert.lua
-- Installing: /home/harry/torch/install/lib/luarocks/rocks/cudnn/scm-1/lua/cudnn/VolumetricMaxPooling.lua
-- Installing: /home/harry/torch/install/lib/luarocks/rocks/cudnn/scm-1/lua/cudnn/Pointwise.lua
-- Installing: /home/harry/torch/install/lib/luarocks/rocks/cudnn/scm-1/lua/cudnn/SpatialSoftMax.lua
-- Installing: /home/harry/torch/install/lib/luarocks/rocks/cudnn/scm-1/lua/cudnn/VolumetricBatchNormalization.lua
-- Installing: /home/harry/torch/install/lib/luarocks/rocks/cudnn/scm-1/lua/cudnn/Pooling3D.lua
-- Installing: /home/harry/torch/install/lib/luarocks/rocks/cudnn/scm-1/lua/cudnn/functional.lua
-- Installing: /home/harry/torch/install/lib/luarocks/rocks/cudnn/scm-1/lua/cudnn/init.lua
-- Installing: /home/harry/torch/install/lib/luarocks/rocks/cudnn/scm-1/lua/cudnn/env.lua
-- Installing: /home/harry/torch/install/lib/luarocks/rocks/cudnn/scm-1/lua/cudnn/SpatialCrossMapLRN.lua
-- Installing: /home/harry/torch/install/lib/luarocks/rocks/cudnn/scm-1/lua/cudnn/SpatialConvolution.lua
-- Installing: /home/harry/torch/install/lib/luarocks/rocks/cudnn/scm-1/lua/cudnn/SpatialMaxPooling.lua
-- Installing: /home/harry/torch/install/lib/luarocks/rocks/cudnn/scm-1/lua/cudnn/TemporalConvolution.lua
-- Installing: /home/harry/torch/install/lib/luarocks/rocks/cudnn/scm-1/lua/cudnn/VolumetricAveragePooling.lua
-- Installing: /home/harry/torch/install/lib/luarocks/rocks/cudnn/scm-1/lua/cudnn/SpatialFullConvolution.lua
-- Installing: /home/harry/torch/install/lib/luarocks/rocks/cudnn/scm-1/lua/cudnn/SpatialBatchNormalization.lua
-- Installing: /home/harry/torch/install/lib/luarocks/rocks/cudnn/scm-1/lua/cudnn/LogSoftMax.lua
-- Installing: /home/harry/torch/install/lib/luarocks/rocks/cudnn/scm-1/lua/cudnn/SoftMax.lua
-- Installing: /home/harry/torch/install/lib/luarocks/rocks/cudnn/scm-1/lua/cudnn/VolumetricConvolution.lua
-- Installing: /home/harry/torch/install/lib/luarocks/rocks/cudnn/scm-1/lua/cudnn/SpatialAveragePooling.lua
-- Installing: /home/harry/torch/install/lib/luarocks/rocks/cudnn/scm-1/lua/cudnn/ReLU.lua
-- Installing: /home/harry/torch/install/lib/luarocks/rocks/cudnn/scm-1/lua/cudnn/SpatialCrossEntropyCriterion.lua
-- Installing: /home/harry/torch/install/lib/luarocks/rocks/cudnn/scm-1/lua/cudnn/SpatialDivisiveNormalization.lua
-- Installing: /home/harry/torch/install/lib/luarocks/rocks/cudnn/scm-1/lua/cudnn/SpatialLogSoftMax.lua
-- Installing: /home/harry/torch/install/lib/luarocks/rocks/cudnn/scm-1/lua/cudnn/BatchNormalization.lua
-- Installing: /home/harry/torch/install/lib/luarocks/rocks/cudnn/scm-1/lua/cudnn/ffi.lua
-- Installing: /home/harry/torch/install/lib/luarocks/rocks/cudnn/scm-1/lua/cudnn/Pooling.lua
Updating manifest for /home/harry/torch/install/lib/luarocks/rocks
cudnn scm-1 is now built and installed in /home/harry/torch/install/ (license: BSD)

**But upon running I get the following:**
harry@harry:~/neural-style$ th neural_style.lua -gpu 0 -backend cudnn
/home/harry/torch/install/bin/luajit: /home/harry/torch/install/share/lua/5.1/trepl/init.lua:384: /home/harry/torch/install/share/lua/5.1/trepl/init.lua:384: /home/harry/torch/install/share/lua/5.1/cudnn/ffi.lua:1278: 'libcudnn (R4) not found in library path.
Please install CuDNN from https://developer.nvidia.com/cuDNN
Then make sure files named as libcudnn.so.4 or libcudnn.4.dylib are placed in your library load path (for example /usr/local/lib , or manually add a path to LD_LIBRARY_PATH)

stack traceback:
	[C]: in function 'error'
	/home/harry/torch/install/share/lua/5.1/trepl/init.lua:384: in function 'require'
	neural_style.lua:64: in function 'main'
	neural_style.lua:500: in main chunk
	[C]: in function 'dofile'
	...arry/torch/install/lib/luarocks/rocks/trepl/scm-1/bin/th:145: in main chunk
	[C]: at 0x00405d70

Also my graphics card at the moment only has 1gb of memory is this too small to use even with cudnn? Any help is appreciated, maybe an updated step by step for cuda 7.5 and cudnn 5 for an idiot such as myself.
Thanks!

**Comment by jcjohnson** [comment]
The master branch of cudnn.torch is expecting cuDNN v4, so it won't work if you install cuDNN 5. I'd recommend sticking with cuDNN 4 for now.

If you are feeling more adventurous, you can install the [R5 branch of cudnn.torch](https://github.com/soumith/cudnn.torch/tree/R5); you may also need to merge [this pull request](https://github.com/soumith/cudnn.torch/pull/159). I haven't yet tried this myself so I'm not sure it will work.

1GB is pretty small - you might run out of memory when you try and load the network off disk.

**Comment by harrydwilde** [comment]
Thanks for the response, I have downloaded v4 but still getting this error :(

harry@harry:~/neural-style$ th neural_style.lua -gpu -0 -backend cudnn
/home/harry/torch/install/bin/luajit: /home/harry/torch/install/share/lua/5.1/trepl/init.lua:384: /home/harry/torch/install/share/lua/5.1/trepl/init.lua:384: /home/harry/torch/install/share/lua/5.1/cudnn/ffi.lua:1278: 'libcudnn (R4) not found in library path.
Please install CuDNN from https://developer.nvidia.com/cuDNN
Then make sure files named as libcudnn.so.4 or libcudnn.4.dylib are placed in your library load path (for example /usr/local/lib , or manually add a path to LD_LIBRARY_PATH)

stack traceback:
	[C]: in function 'error'
	/home/harry/torch/install/share/lua/5.1/trepl/init.lua:384: in function 'require'
	neural_style.lua:64: in function 'main'
	neural_style.lua:500: in main chunk
	[C]: in function 'dofile'
	...arry/torch/install/lib/luarocks/rocks/trepl/scm-1/bin/th:145: in main chunk
	[C]: at 0x00405d70

**Comment by jcjohnson** [comment]
You need to make sure that the libraries are on your LD_LIBRARY_PATH. In a shell, type the following:

```bash
echo $LD_LIBRARY_PATH
```

This will show a list of directories separated by colons; you need to make sure that the file libcudnn.so.4 is in one of those directories.

**Comment by harrydwilde** [comment]
I get this:
/home/ubuntu/cudnn-6.5-linux-x64-v2:/home/harry/torch/install/lib:/home/harry/torch/install/lib:
how do I add to it?

**Comment by harrydwilde** [comment]
Nevermind I figured it out, it works! Works great on default sizes I wonder how large I can go

**Comment by StryxZilla** [comment]
Has anyone seen how to have 2 versions of cuda installed concurrently, or does anyone have a neural-style implementation that works on CUDA 7.5?

**Comment by henrylee2570** [comment]
@harrydwilde Could you please kindly explain how you got it work? I'm getting the exact same error now and couldn't find the `libcudnn.so.number` anywhere...... do I have to reinstall cudnn from NVIDIA to get the `libcudnn.so.number` ? Thanks a lot!!!
