### ISSUE TITLE
VGG_ILSVRC_19_layers model unavailable

### ISSUE THREAD

**Issue by perfectritone** [jcjohnson/neural-style#202]
When running the test script, I get an error:
```
Couldn't load models/VGG_ILSVRC_19_layers.caffemodel
~/code/torch/install/bin/luajit: neural_style.lua:73: attempt to index a nil value
```
It turns out that the model it's looking for was never downloaded. When I run this command by itself, it doesn't find anything.
```
wget -c http://www.robots.ox.ac.uk/~vgg/software/very_deep/caffe/VGG_ILSVRC_19_layers.caffemodel 
```

Is there somewhere else I can find this file?

**Comment by hexus** [comment]
I have the same problem, this host simply doesn't respond.

**Comment by htoyryla** [comment]
The VGG19 caffemodel on this page (found by google) appears to be identical with the original
https://worksheets.codalab.org/bundles/0x54101cad2a56410c843b14153371aa5c/
