### ISSUE TITLE
VGG_ILSVRC_19_layers unreachable

### ISSUE THREAD

**Issue by ironvault** [jcjohnson/neural-style#203]
It seems that the Robotics department site at Oxford is down so I'm not able to download the VGG_ILSVRC_19_layers.caffemodel file. 

Are there any mirror sources or is anyone willing to make one available in the meantime?
it would be greatly appreciated!

**Comment by hexus** [comment]
Check out the issue posted before yours:

https://github.com/jcjohnson/neural-style/issues/202#issuecomment-207736263

**Comment by ironvault** [comment]
Thanks a ton!! I was about to give up and call it a night..
