### ISSUE TITLE
WARNING: Skipping content loss

### ISSUE THREAD

**Issue by Siend** [jcjohnson/neural-style#213]
root@si-VirtualBox:~/neural-style# th neural_style.lua -style_image ~/2.jpg -content_image ~/1.jpg -gpu -1
[libprotobuf WARNING google/protobuf/io/coded_stream.cc:537] Reading dangerously large protocol message.  If the message turns out to be larger than 1073741824 bytes, parsing will be halted for security reasons.  To increase the limit (or to disable these warnings), see CodedInputStream::SetTotalBytesLimit() in google/protobuf/io/coded_stream.h.
[libprotobuf WARNING google/protobuf/io/coded_stream.cc:78] The total number of bytes read was 574671192
Successfully loaded models/VGG_ILSVRC_19_layers.caffemodel
conv1_1: 64 3 3 3
conv1_2: 64 64 3 3
conv2_1: 128 64 3 3
conv2_2: 128 128 3 3
conv3_1: 256 128 3 3
conv3_2: 256 256 3 3
conv3_3: 256 256 3 3
conv3_4: 256 256 3 3
conv4_1: 512 256 3 3
conv4_2: 512 512 3 3
conv4_3: 512 512 3 3
conv4_4: 512 512 3 3
conv5_1: 512 512 3 3
conv5_2: 512 512 3 3
conv5_3: 512 512 3 3
conv5_4: 512 512 3 3
fc6: 1 1 25088 4096
fc7: 1 1 4096 4096
fc8: 1 1 4096 1000
Setting up style layer  	2	:	relu1_1	
Setting up style layer  	7	:	relu2_1	
Setting up style layer  	12	:	relu3_1	
Setting up style layer  	21	:	relu4_1	
Setting up content layer	23	:	relu4_2	
Setting up style layer  	30	:	relu5_1	
WARNING: Skipping content loss	

images in attach:
![1](https://cloud.githubusercontent.com/assets/3957692/14887870/c43e519e-0d68-11e6-93c3-f56f8be009c5.jpg)
![2](https://cloud.githubusercontent.com/assets/3957692/14887882/ca73bb1c-0d68-11e6-8c19-64ccfae336e5.jpg)

**Comment by htoyryla** [comment]
WARNING: Skipping content loss 
is normal at the beginning when the layers and their loss modules are being set up. So far there is nothing unusual in your output.

If the problem is that nothing happens after this for a long time, use -print_iter 1 to see if anything is happening.

**Comment by Siend** [comment]
Running optimization with L-BFGS	

so i need just w8?

**Comment by htoyryla** [comment]
With enough memory, a reasonable cpu and -print_iter 1 you should not need to wait long. I get the the iteration in about 10 seconds, with a less powerful CPU it could take more but if nothing happens in 10 minutes or so then something is probably wrong.

**Comment by Siend** [comment]
ok, thx)
