### ISSUE TITLE
Interesting application beyond transferring artistic style

### ISSUE THREAD

**Issue by ProGamerGov** [jcjohnson/neural-style#229]
![](https://i.imgur.com/u4IkA6y.jpg)

![](https://i.imgur.com/IACI7Tf.jpg)

![](https://i.imgur.com/wNcInt9.png)

**Comment by jcjohnson** [comment]
Apparently it's impossible to delete issues:

https://github.com/isaacs/github/issues/253

That's annoying.

**Comment by ProGamerGov** [comment]
@jcjohnson That sucks, I was posting this for a method of using a combination of models to create higher quality images, but I figured the wiki is a more appropriate location.
