### ISSUE TITLE
Some personal questions

### ISSUE THREAD

**Issue by lmelody** [jcjohnson/neural-style#235]
I want to know how to generate each layer independent feature images,such as relu4_2 . 
Hope I can get the answer

**Comment by lmelody** [comment]
SOS

**Comment by jcjohnson** [comment]
Sorry, I don't understand the question. Do you want to generate images using features from only a single layer? If that's the case then use the `-content_layers` and `-style_layers` flags to set the active layers.

**Comment by lmelody** [comment]
thanks
