### ISSUE TITLE
CUDNN Install Issue

### ISSUE THREAD

**Issue by StryxZilla** [jcjohnson/neural-style#239]
I am getting the following error when trying to install CUDNN.  I have CUDA 7.0 installed.  I am unsure why CUDNN V4 is looking for CUDA 7.5.  Any thoughts?

stryx@Andy-Ubuntu:~$ luarocks install cudnn
Installing https://raw.githubusercontent.com/torch/rocks/master/cudnn-scm-1.rockspec...
Using https://raw.githubusercontent.com/torch/rocks/master/cudnn-scm-1.rockspec... switching to 'build' mode
Cloning into 'cudnn.torch'...
remote: Counting objects: 51, done.
remote: Compressing objects: 100% (43/43), done.
remote: Total 51 (delta 17), reused 22 (delta 6), pack-reused 0
Receiving objects: 100% (51/51), 49.12 KiB | 0 bytes/s, done.
Resolving deltas: 100% (17/17), done.
Checking connectivity... done.
cmake -E make_directory build && cd build && cmake .. -DCMAKE_BUILD_TYPE=Release -DCMAKE_PREFIX_PATH="/home/stryx/torch/install/bin/.." -DCMAKE_INSTALL_PREFIX="/home/stryx/torch/install/lib/luarocks/rocks/cudnn/scm-1" && make

-- The C compiler identification is GNU 4.8.4
-- The CXX compiler identification is GNU 4.8.4
-- Check for working C compiler: /usr/bin/cc
-- Check for working C compiler: /usr/bin/cc -- works
-- Detecting C compiler ABI info
-- Detecting C compiler ABI info - done
-- Check for working CXX compiler: /usr/bin/c++
-- Check for working CXX compiler: /usr/bin/c++ -- works
-- Detecting CXX compiler ABI info
-- Detecting CXX compiler ABI info - done
-- Found Torch7 in /home/stryx/torch/install
CMake Error at /usr/share/cmake-2.8/Modules/FindPackageHandleStandardArgs.cmake:108 (message):
  Could NOT find CUDA: Found unsuitable version "7.0", but required is at
  least "7.5" (found /usr/local/cuda)
Call Stack (most recent call first):
  /usr/share/cmake-2.8/Modules/FindPackageHandleStandardArgs.cmake:313 (_FPHSA_FAILURE_MESSAGE)
  /usr/share/cmake-2.8/Modules/FindCUDA.cmake:806 (find_package_handle_standard_args)
  CMakeLists.txt:9 (FIND_PACKAGE)

-- Configuring incomplete, errors occurred!
See also "/tmp/luarocks_cudnn-scm-1-4612/cudnn.torch/build/CMakeFiles/CMakeOutput.log".

Error: Build error: Failed building.

**Comment by StryxZilla** [comment]
So I think that the newest torch bindings grap CUDNN R5.  Can someone give me some advice on how to make the luarocks installer grab R4 bindings for torch?

**Comment by StryxZilla** [comment]
Got this working.  Cloned the R4 branch.  used luarocks make to install bindings from that branch.  Adding path to cuda lib64 directory to LD_LIBRARY_PATH and restarting terminal got everything working with cudnn.

**Comment by CosminPOP** [comment]
StryxZilla care to elaborate ?
