### ISSUE TITLE
segmentation fault when size > 2176x1631

### ISSUE THREAD

**Issue by dasantonym** [jcjohnson/neural-style#24]
i am running the cpu version on an instance with 240gb of ram. when i set the size to 2176x1631 it works and the memory consumption stays at about 72gb. now if i set the size to anything above that i get a segmentation fault right after initialisation.

is there some technical limit to the image size apart from the available ram?

**Comment by SirSpunky** [comment]
Sorry, I don't have an answer, but I just have to ask: how did you get that much RAM?! :)  That's just incredible. How long does it take to generate those images?

**Comment by jcjohnson** [comment]
I'm also not sure what the problem might be - do you get a stack trace, or just a segfault?

**Comment by dasantonym** [comment]
it's an aws r3.8xlarge instance (32 vcpus, 244gb ram) and it takes about 15h for 1000 iterations at this resolution.

i am only getting the segfault, no stacktrace. i'll have a closer look at it tomorrow and try to see where it actually happens.

**Comment by lolz0r** [comment]
I see the same issue - also using amazon r3.8xlarge.

**Comment by dasantonym** [comment]
i now know it always happens the second time line 120 in neural_style.lua is called.
https://github.com/jcjohnson/neural-style/blob/15ad5e5/neural_style.lua#L120

the segmentation fault is an error code 6 so a write to memory results in a page not found.

so apparently it is a memory allocation issue and that could very well be an os-specific configuration problem (although the kernel config looked fine at first glance). then again it could also be related to luajit and i am no lua expert.

will have another shot at this later this week i guess. maybe someone has some hints on what to look at for debugging.

**Comment by lolz0r** [comment]
I have read things to the effect that luajit has an internal memory limit of 1GB for lua based objects; it is possible that at higher resolution we are hitting this memory ceiling. One possible fix that I am going to explore today is to use normal lua instead of luajit and see if the issue still occurs.

**Comment by lolz0r** [comment]
I tried replacing the lua runtime with a non-jit version, updating open blas to a patch that spoke about segfault issues, ran with extra debugging enabled in luajit and prayed to the software gods. The best lead I have is that it seems to crash out on the while processing the 5th layer within net:forward() in the same place that @dasantonym saw.

Perhaps we can try using a different blas package, such as mkl? If only we had easy access to it...

**Comment by lolz0r** [comment]
Linking with MKL does nothing to fix this issue. I don't know what else to try.

**Comment by quematech** [comment]
Did you try the recently added adam option ?

**Comment by dasantonym** [comment]
oh wow, a lot happened here over the week. i am not sure if pursuing the cpu based method is feasible. even if you manage to use up all of the 240gb ram then it will still be limited and the resolution mentioned above takes something like 15h... that will take ages if you go for really high resolutions.

so, i am probably going to try overlapping tiles and then let a stitcher assemble them, but i am also curious if you couldn't use mpi (https://github.com/sixin-zh/mpiT) and run it on a scalable gpu cluster with a unified virtual address space for the memory.

also, i am closing this issue because i do not see it really related to this repo. the segfault is most likely either something related to torch and/or the os.

the discussion on this should rather continue here:
https://github.com/jcjohnson/neural-style/issues/36

**Comment by anastasiuspernat** [comment]
This bug really belonged to Torch/nn and must have been fixed with my recent pull request
https://github.com/torch/nn/pull/443

Hope it finally works on big images!

**Comment by jcjohnson** [comment]
Wow, nice find! I have never tried to run with images that big, but it's good that it works now!
