### ISSUE TITLE
cuDNN install problem.

### ISSUE THREAD

**Issue by lgs777** [jcjohnson/neural-style#245]
When I install cuDNN with luarocks install cudnn command.
How can I solve this? plz help me!

========================================================
root@goonseob-To-be-filled-by-O-E-M:/home/goonseob/NeuralArt/neural-style# luarocks install cudnn
Installing https://raw.githubusercontent.com/torch/rocks/master/cudnn-scm-1.rockspec...
Using https://raw.githubusercontent.com/torch/rocks/master/cudnn-scm-1.rockspec... switching to 'build' mode
Cloning into 'cudnn.torch'...
remote: Counting objects: 51, done.
remote: Compressing objects: 100% (43/43), done.
remote: Total 51 (delta 17), reused 20 (delta 6), pack-reused 0
Receiving objects: 100% (51/51), 48.51 KiB | 0 bytes/s, done.
Resolving deltas: 100% (17/17), done.
Checking connectivity... done.
cmake -E make_directory build && cd build && cmake .. -DCMAKE_BUILD_TYPE=Release -DCMAKE_PREFIX_PATH="/usr/local/bin/.." -DCMAKE_INSTALL_PREFIX="/usr/local/lib/luarocks/rocks/cudnn/scm-1" && make

-- The C compiler identification is GNU 4.8.4
-- The CXX compiler identification is GNU 4.8.4
-- Check for working C compiler: /usr/bin/cc
-- Check for working C compiler: /usr/bin/cc -- works
-- Detecting C compiler ABI info
-- Detecting C compiler ABI info - done
-- Check for working CXX compiler: /usr/bin/c++
-- Check for working CXX compiler: /usr/bin/c++ -- works
-- Detecting CXX compiler ABI info
-- Detecting CXX compiler ABI info - done
-- Found Torch7 in /usr/local
CMake Error at /usr/share/cmake-2.8/Modules/FindPackageHandleStandardArgs.cmake:108 (message):
  Could NOT find CUDA: Found unsuitable version "7.0", but required is at
  least "7.5" (found /usr/local/cuda)
Call Stack (most recent call first):
  /usr/share/cmake-2.8/Modules/FindPackageHandleStandardArgs.cmake:313 (_FPHSA_FAILURE_MESSAGE)
  /usr/share/cmake-2.8/Modules/FindCUDA.cmake:806 (find_package_handle_standard_args)
  CMakeLists.txt:9 (FIND_PACKAGE)

-- Configuring incomplete, errors occurred!
See also "/tmp/luarocks_cudnn-scm-1-44/cudnn.torch/build/CMakeFiles/CMakeOutput.log".

Error: Build error: Failed building.

**Comment by jcjohnson** [comment]
Your CUDA install is outdated; cudnn.torch wants CUDA 7.5 but you have CUDA 7.0 installed.

**Comment by CosminPOP** [comment]
just ran into this problem myself,
i used ubuntu 12.04 and I think I can't install cuda 7.5 on 12.04
will probably try again tomorrow with ubuntu 14 or 15
