### ISSUE TITLE
cuDNN command error

### ISSUE THREAD

**Issue by lgs777** [jcjohnson/neural-style#247]
when I type " th neural_style.lua -gpu 0 -backend cudnn" 
How can I solve this? plz help me!

root@goonseob-To-be-filled-by-O-E-M:/home/goonseob/NeuralArt/neural-style# th neural_style.lua -gpu 0 -backend cudnn
nil	
/usr/local/bin/luajit: /usr/local/share/lua/5.1/trepl/init.lua:384: /usr/local/share/lua/5.1/trepl/init.lua:384: /usr/local/share/lua/5.1/cudnn/ffi.lua:1599: 'libcudnn (R5) not found in library path.
Please install CuDNN from https://developer.nvidia.com/cuDNN
Then make sure files named as libcudnn.so.5 or libcudnn.5.dylib are placed in your library load path (for example /usr/local/lib , or manually add a path to LD_LIBRARY_PATH)

stack traceback:
	[C]: in function 'error'
	/usr/local/share/lua/5.1/trepl/init.lua:384: in function 'require'
	neural_style.lua:64: in function 'main'
	neural_style.lua:500: in main chunk
	[C]: in function 'dofile'
	/usr/local/lib/luarocks/rocks/trepl/scm-1/bin/th:145: in main chunk
	[C]: at 0x00406260
root@goonseob-To-be-filled-by-O-E-M:/home/goonseob/NeuralArt/neural-style#

**Comment by electronsarapis** [comment]
I've got the same problem and doing 
`sudo cp cuda/lib64/libcudnn* /usr/local/cuda-7.0/lib64/`
`sudo cp cuda/include/cudnn.h /usr/local/cuda-7.0/include/` 
doesn't seem to work

**Comment by Runescaped** [comment]
I had the same issue, but solved it using:

`export LD_LIBRARY_PATH=/usr/local/cuda-7.5/lib64:$LD_LIBRARY_PATH`

After finding it in [this thread](https://github.com/jcjohnson/neural-style/issues/154)

**Comment by electronsarapis** [comment]
Have done this with no luck. Same error as before.

**Comment by Runescaped** [comment]
Weird...and you didn't have any issues installing cudnn?

**Comment by aedelsten** [comment]
I was able to install cudnn (that is `luarocks install cudnn` succeeds) but I get the same error. On my server, cuDNN 4 is installed with lib's located in `/usr/lib/x86_64-linux-gnu` which is in my load lib path. 

```
~/git/neural-style$ set | grep LD_LIBRARY
LD_LIBRARY_PATH=/home/xyz/git/torch/install/lib:/usr/lib/x86_64-linux-gnu:
/usr/local/lib/:/usr/local/nvidia/lib:/usr/local/nvidia/lib64:
~/git/neural-style$   
~/git/neural-style$ ls /usr/lib/x86_64-linux-gnu/libcudnn*
/usr/lib/x86_64-linux-gnu/libcudnn.so        /usr/lib/x86_64-linux-gnu/libcudnn_static.a
/usr/lib/x86_64-linux-gnu/libcudnn.so.4      /usr/lib/x86_64-linux-gnu/libcudnn_static_v4.a
/usr/lib/x86_64-linux-gnu/libcudnn.so.4.0.7
~/git/neural-style$   
```

In the neural-style [install instructions](https://github.com/jcjohnson/neural-style/blob/master/INSTALL.md) (optional step 6) it states to download/use "Version 4" of cuDNN. Has that now changed to **version 5**?

For now, I'll remove the "-backend" option and just go with the default backend for "-gpu 0" (which I think is "nn").

**Comment by aedelsten** [comment]
Hmm... yes, I think Torch might have been updated and now one of the libs requires cuDNN 5.

`/git/torch/install/share/lua/5.1/cudnn/ffi.lua` now needs 5.0 bindings.

Top of the file has the CUDDN_MAJOR as "5" now... and they look explicitly for the 5 libs:

`local libnames = {'libcudnn.so.5', 'libcudnn.5.dylib'}`

**Comment by tastyminerals** [comment]
Having the same issue. I downloaded a cudnn package with **libcudnn.so.5** from nvidia web site and put it in a local dir `/local/pavels/cuda5/lib/`. I added this dir to `$LD_LIBRARY_PATH`: 
```
export LD_LIBRARY_PATH=/usr/lib/x86_64-linux-gnu/:/usr/lib/:/local/pavels/cuda5/lib/
```
`source ~/.bashrc`, yet, nothing changed.

**Comment by eliksr** [comment]
@tastyminerals did you found the solution?

**Comment by tastyminerals** [comment]
@eliksr No, I did the training without cuda optimization.
