### ISSUE TITLE
Dumb question from a painter

### ISSUE THREAD

**Issue by thedonquixotic** [jcjohnson/neural-style#253]
Hi, I'm an artist/designer who is learning code tools as a side project and for fun. I wanted to use the neural-style stuff for some experiments, and I think I have most everything working. It's running right now (cpu only, wanted to test it before I did all the cuda stuff) and I was wondering where the image output to? Like I run the script, given in the installation guide, it's running right now, but does it out put the render to a specific place on the hdd?

**Comment by 3DTOPO** [comment]
Unless you specify the output image, it is written to output.png in your neural-style folder.

**Comment by thedonquixotic** [comment]
Excellent, I see that now. Thank you.
