### ISSUE TITLE
cannot open neural_style.lua: No such file or directory

### ISSUE THREAD

**Issue by thedonquixotic** [jcjohnson/neural-style#259]
So I finally got the Ubuntu install working. Should have just done a dual boot from the beginning, so much easier than trying to do the USB thing. 

Went through the entire install guide, everything seemed to be going pretty smoothly. I'd already done it once so it didn't seem like it would be that hard. 

I got up to the sixth step (installing the cudnn backend) when I started getting problems due to the install.md being out of date. So I decided to just go back and run it off gpu and test it out, but ran into a weird problem. See the error readout here:

`th neural_style.lua -gpu -1 -print_iter 1
/home/david/torch/install/bin/luajit: cannot open neural_style.lua: No such file or directory
stack traceback:
    [C]: in function 'dofile'
    ...avid/torch/install/lib/luarocks/rocks/trepl/scm-1/bin/th:145: in main chunk
    [C]: at 0x00406670
`

That used to work! That's without gpu. now it doesn't. And with GPU I get basically the same readout. I don't know what happened.... maybe trying to install the cudnn messed something up? Or maybe I thought I had properly installed neural style but hadn't? when I try to reinstall it by running the code on the install.md it just says that it's already been installed. Any clue on where I'm going wrong?

It looks like something related to luarocks maybe?

**Comment by htoyryla** [comment]
David French <notifications@github.com> kirjoitti 22.6.2016 kello 20.36:

> th neural_style.lua -gpu -1 -print_iter 1
> /home/david/torch/install/bin/luajit: cannot open neural_style.lua: No such file or directory
> stack traceback:
> [C]: in function 'dofile'
> ...avid/torch/install/lib/luarocks/rocks/trepl/scm-1/bin/th:145: in main chunk
> [C]: at 0x00406670
> 
> That used to work! That's without gpu. now it doesn't. And with GPU I get basically the same readout. I don't know what happened.... maybe trying to install the cudnn messed something up? Or maybe I thought I had properly installed neural style but hadn't? when I try to reinstall it by running the code on the install.md it just says that it's already been installed. Any clue on where I'm going wrong?
> 
You need to be in the neural-style directory when you th neural-style.lua.

**Comment by thedonquixotic** [comment]
Ah thanks, I'll do that. thank you.

**Comment by thedonquixotic** [comment]
Okay, I seem to be having the same or a similar problem: 

I put in 
`cd ~/neural-style

th neural_style.lua -style_image <brad_pitt.jpg> -content_image <escher_sphere.jpg> -gpu 0`

and I have the two images in my neural-style folder

And I get this response:

`[libprotobuf WARNING google/protobuf/io/coded_stream.cc:505] Reading dangerously large protocol message.  If the message turns out to be larger than 1073741824 bytes, parsing will be halted for security reasons.  To increase the limit (or to disable these warnings), see CodedInputStream::SetTotalBytesLimit() in google/protobuf/io/coded_stream.h.
[libprotobuf WARNING google/protobuf/io/coded_stream.cc:78] The total number of bytes read was 574671192
/home/david/torch/install/bin/luajit: /home/david/torch/install/share/lua/5.1/image/init.lua:347: 0: No such file or directory
stack traceback:
	[C]: in function 'error'
	/home/david/torch/install/share/lua/5.1/image/init.lua:347: in function 'load'
	neural_style.lua:90: in function 'main'
	neural_style.lua:515: in main chunk
	[C]: in function 'dofile'
	...avid/torch/install/lib/luarocks/rocks/trepl/scm-1/bin/th:145: in main chunk
	[C]: at 0x00406670
`

I'm guessing this might have something to do with the Google libprotobuf library mentioned in the installation guide? I'll try reinstalling that and see if that helps.

**Comment by thedonquixotic** [comment]
Also I should clarify, it works as expected when I just run the test code :

`th neural_style.lua -gpu -1 -print_iter 1`

**Comment by jcjohnson** [comment]
To use your own content and style images you need to actually provide the paths to the images on the command line:

```bash
th neural_style.lua -style_image my_style.jpg -content_image my_content.jpg -gpu 0
```

**Comment by thedonquixotic** [comment]
Sorry, I accidentally copy pasted the wrong thing. The thing I'm in putting is:
`th neural_style.lua -style_image <brad_pitt.jpg> -content_image <escher_sphere.jpg> -gpu 0`

If the image files are in the neural-style folder do they need to be specified further or does it treat it relative? I only have experience with Processing and that's how that works from the stuff I've done there.

**Comment by thedonquixotic** [comment]
Oh is it the angle brackets? let me try that.

**Comment by jcjohnson** [comment]
Yep, you don't need the angle brackets

**Comment by thedonquixotic** [comment]
Bingo, yeah, thank you. Once again, thank you for your patience. I know I'm just an artist bungling into ya'lls project here, but I thank you and everyone else for the help they've given. I'm really excited by this stuff! I'll try to get a guide up on Medium soon, once I have something to actually show for it.  and get a better handle on things.

**Comment by thedonquixotic** [comment]
done. Finally got out my first article: Thank you so much @jcjohnson 
Here's a link! https://medium.com/@davidaslanfrench/how-artists-can-use-neural-networks-to-make-art-714cdab53953#.1nfak25av
