### ISSUE TITLE
Ubuntu: loadcaffe.lua:20: attempt to index a nil value

### ISSUE THREAD

**Issue by mrlament** [jcjohnson/neural-style#264]
Hi everyone,

I'm executing this:

`th neural_style.lua -style_image Painting1.jpg -content_image Image1.jpg -gpu -1`

and it's not finishing.  Here's the response I get:

> [libprotobuf WARNING google/protobuf/io/coded_stream.cc:537] Reading dangerously large protocol message.  If the message turns out to be larger than 1073741824 bytes, parsing will be halted for security reasons.  To increase the limit (or to disable these warnings), see CodedInputStream::SetTotalBytesLimit() in google/protobuf/io/coded_stream.h.
> [libprotobuf WARNING google/protobuf/io/coded_stream.cc:78] The total number of bytes read was 574671192
> Successfully loaded models/VGG_ILSVRC_19_layers.caffemodel
> /home/duke/torch/install/bin/luajit: ...duke/torch/install/share/lua/5.1/loadcaffe/loadcaffe.lua:20: attempt to index a nil value
> stack traceback:
> 	...duke/torch/install/share/lua/5.1/loadcaffe/loadcaffe.lua:20: in function 'load'
> 	neural_style.lua:73: in function 'main'
> 	neural_style.lua:515: in main chunk
> 	[C]: in function 'dofile'
> 	...duke/torch/install/lib/luarocks/rocks/trepl/scm-1/bin/th:145: in main chunk
> 	[C]: at 0x00405d50

I'm running Ubuntu 16.04.  Anyone have any ideas?

**Comment by halstedlarsson** [comment]
Could be that your model file is missing or damaged. Did you run the model install script? It has to be run sepa
rately after install.

**Comment by mrlament** [comment]
Thanks.  I already did.   I went ahead and ran it again just now to check with:

`sh models/download_models.sh`

and it says "The file is fully retrieved; nothing to do"

Any other ideas?

**Comment by humppa** [comment]
Loadcaffe is not very friendly with error messages, and there are many possibilities, what could have gone wrong.

Since loadcaffe tries to transform prototxt file to Lua file, it needs to be able to create a new file to `models` directory. One way I've gotten the aforementioned error was, when I cloned `neutral-style` with superuser privileges and tried to ran it as a regular user (without sufficient write permission).

Does the file `VGG_ILSVRC_19_layers_deploy.prototxt.lua` appear to `models` directory?

Also, to rule out the possibility of corrupted files, here are the sha1sums of the models:
```
239785e7862442717d831f682bb824055e51e9ba  VGG_ILSVRC_19_layers.caffemodel
132d2f60b3d3b1c2bb9d3fdb0c8931a44f89e2ae  VGG_ILSVRC_19_layers_deploy.prototxt
a74d3f83f8b719b14f78a1d0a5ea9b5c749d53d7  vgg_normalised.caffemodel
```

**Comment by DimaKudosh** [comment]
What version of gcc/g++ you are using? (You can check it using 'gcc -v' command). If your version <5 you must update it.

**Comment by mrlament** [comment]
Hi everyone,

Thanks for the feedback.  I've tried all of the suggestions and am still having the problem.  I think at this point I'm just going to try installing it on another machine.  

Thanks!

**Comment by Noah-Kennedy** [comment]
I'm having this issue as well on Ubuntu 16.04.  I have tried this across multiple machines. Any thoughts or ideas?

**Comment by GeneralKnowledge** [comment]
I ran into this issue. I didn't the correct permissions set on the folder. 
`sudo th neural_style.lua -style_image YOURPAINTINGHERE.jpg - content_image YOURPHOTOHERE.jpg -gpu -1`
worked but I ended up correcting my permission problems
