### ISSUE TITLE
No Output

### ISSUE THREAD

**Issue by tegarkurniawan** [jcjohnson/neural-style#267]
I did try and run but no output image
code : 
th neural_style.lua -gpu -1 -style_image examples/inputs/picasso_selfport1907.jpg -content_image examples/inputs/brad_pitt.jpg -output_image profile.png -model_file models/VGG_ILSVRC_19_layers.caffemodel -proto_file models/VGG_ILSVRC_19_layers_deploy.prototxt -content_weight 10 -style_weight 250 -image_size 250 -print_iter 1

output code: 
[libprotobuf WARNING google/protobuf/io/coded_stream.cc:505] Reading dangerously large protocol message.  If the message turns out to be larger than 1073741824 bytes, parsing will be halted for security reasons.  To increase the limit (or to disable these warnings), see CodedInputStream::SetTotalBytesLimit() in google/protobuf/io/coded_stream.h.
[libprotobuf WARNING google/protobuf/io/coded_stream.cc:78] The total number of bytes read was 574671192
Successfully loaded models/VGG_ILSVRC_19_layers.caffemodel
conv1_1: 64 3 3 3
conv1_2: 64 64 3 3
conv2_1: 128 64 3 3
conv2_2: 128 128 3 3
conv3_1: 256 128 3 3
conv3_2: 256 256 3 3
conv3_3: 256 256 3 3
conv3_4: 256 256 3 3
conv4_1: 512 256 3 3
conv4_2: 512 512 3 3
conv4_3: 512 512 3 3
conv4_4: 512 512 3 3
conv5_1: 512 512 3 3
conv5_2: 512 512 3 3
conv5_3: 512 512 3 3
conv5_4: 512 512 3 3
fc6: 1 1 25088 4096
fc7: 1 1 4096 4096
fc8: 1 1 4096 1000
Setting up style layer  	2	:	relu1_1	
Setting up style layer  	7	:	relu2_1	
Setting up style layer  	12	:	relu3_1	
Setting up style layer  	21	:	relu4_1	
Setting up content layer	23	:	relu4_2	
Setting up style layer  	30	:	relu5_1	
Running optimization with L-BFGS	
Iteration 1 / 1000	
  Content 1 loss: 6830778.125000	
  Style 1 loss: 156138.580322	
  Style 2 loss: 20665453.125000	
  Style 3 loss: 6607033.203125	
  Style 4 loss: 252967109.375000	
  Style 5 loss: 21495.241165	
  Total loss: 287248007.649612	
<optim.lbfgs> 	creating recyclable direction/step/history buffers	
Iteration 2 / 1000	
  Content 1 loss: 6830768.125000	
  Style 1 loss: 156138.580322	
  Style 2 loss: 20665453.125000	
  Style 3 loss: 6607033.203125	
  Style 4 loss: 252967109.375000	
  Style 5 loss: 21495.241165	
  Total loss: 287247997.649612	
Iteration 3 / 1000	
  Content 1 loss: 6330779.375000	
  Style 1 loss: 139395.187378	
  Style 2 loss: 15094379.882812	
  Style 3 loss: 5382623.046875	
  Style 4 loss: 204632218.750000	
  Style 5 loss: 20202.121735	
  Total loss: 231599598.363800	
Iteration 4 / 1000	
  Content 1 loss: 380513320.000000	
  Style 1 loss: 6452613.769531	
  Style 2 loss: 4886064000.000000	
  Style 3 loss: 8913999000.000000	
  Style 4 loss: 1254110464000.000000	
  Style 5 loss: 594051125.000000	
  Total loss: 1268891544058.769531	
Iteration 5 / 1000	
  Content 1 loss: 6332839.375000	
  Style 1 loss: 139340.881348	
  Style 2 loss: 15071003.906250	
  Style 3 loss: 5368807.128906	
  Style 4 loss: 203264937.500000	
  Style 5 loss: 20150.247574	
  Total loss: 230197079.039078	

whether it can be without being able to install CUDA ?

**Comment by 3DTOPO** [comment]
Did you let it get to integration 1000? By default it saves an intermediate image every 100 iterations - so that is the soonest you would see any images output unless you use the save_iter flag.

**Comment by tegarkurniawan** [comment]
I'm only up to 5 because of the integration of a very long , how long I have to wait until 1000 integration ?

**Comment by 3DTOPO** [comment]
Unless you use your GPU, it will take a very long time. You use the save_iter flag to specify that you want images written maybe every 5 or 10 iterations (for example: -save_iter 10) - but it typically takes hundreds of iterations to look like anything useful.

**Comment by tegarkurniawan** [comment]
I have added -save_inter 100 but old 
code :
th neural_style.lua -gpu -1 -style_image examples/inputs/picasso_selfport1907.jpg -content_image examples/inputs/brad_pitt.jpg -output_image profile.png -model_file models/VGG_ILSVRC_19_layers.caffemodel -proto_file models/VGG_ILSVRC_19_layers_deploy.prototxt -content_weight 10 -style_weight 250 -image_size 250 -save_iter 100

how long to get the picture output ?

**Comment by 3DTOPO** [comment]
100 is the default - so you didn't change anything and you will have to wait until iteration 100 before you see any images output.

**Comment by tegarkurniawan** [comment]
100 is max interation ?  
if I change my code: 
th neural_style.lua -gpu -1 -style_image examples/inputs/picasso_selfport1907.jpg -content_image examples/inputs/brad_pitt.jpg -output_image profile.png -model_file models/VGG_ILSVRC_19_layers.caffemodel -proto_file models/VGG_ILSVRC_19_layers_deploy.prototxt -content_weight 10 -style_weight 250 -image_size 250 -save_iter 10

do i have to wait till 10 iteration for get output picture ?

**Comment by 3DTOPO** [comment]
> 100 is max interation ?

By default 1000 is max. By default it writes one image every 100 iterations.

>do i have to wait till 10 iteration for get output picture ?

Correct.

**Comment by tegarkurniawan** [comment]
thanks i already get the output image , but I felt too long to get a perfect result , do you have any suggestions?

**Comment by 3DTOPO** [comment]
It often takes some experimenting to tune results. Also, check the wiki and there are some helpful threads here.

You'll want to get a supported GPU - it is like ~100 times faster.
