### ISSUE TITLE
Updating Neural-style

### ISSUE THREAD

**Issue by jbgrant01** [jcjohnson/neural-style#269]
Newbie to Github here. I installed neural-style several months back and I know you are active in releasing new versions. Does my installation automagically update or do I have to tell it to update? I tried to "git clone https://github.com/jcjohnson/neural-style.git" but it complained that the neural-style directory was not empty. I don't want to wipe my present directory. I could rename it then move what I need over later, but I figure there must be an easier way.

I searched the Issues and wiki, but didn't find anything. Sorry for the newbie question.

**Comment by atonn** [comment]
Hi, usually there is no automatic update taking place, and the clone command is for the initial creation only. 

do "git pull" inside the neural-style directory to update to the latest version.

**Comment by jbgrant01** [comment]
Thanks. That was fast!
