### ISSUE TITLE
Kepler (GTX 670) Failing to run?

### ISSUE THREAD

**Issue by fdimitri** [jcjohnson/neural-style#271]
Installed CUDA 8.0 rc, cudnn.. GPU 0,1 work fine (GTX 750 Ti), GPU 2 (GTX 670) fails early

[root@elementium neural-style]# th neural_style.lua -gpu 2 -backend cudnn -content_image ./shed.jpg  -style_image ./examples/inputs/golden_gate.jpg
[libprotobuf WARNING google/protobuf/io/coded_stream.cc:537] Reading dangerously large protocol message.  If the message turns out to be larger than 1073741824 bytes, parsing will be halted for security reasons.  To increase the limit (or to disable these warnings), see CodedInputStream::SetTotalBytesLimit() in google/protobuf/io/coded_stream.h.
[libprotobuf WARNING google/protobuf/io/coded_stream.cc:78] The total number of bytes read was 574671192
Successfully loaded models/VGG_ILSVRC_19_layers.caffemodel
conv1_1: 64 3 3 3
conv1_2: 64 64 3 3
conv2_1: 128 64 3 3
conv2_2: 128 128 3 3
conv3_1: 256 128 3 3
conv3_2: 256 256 3 3
conv3_3: 256 256 3 3
conv3_4: 256 256 3 3
conv4_1: 512 256 3 3
conv4_2: 512 512 3 3
conv4_3: 512 512 3 3
conv4_4: 512 512 3 3
conv5_1: 512 512 3 3
conv5_2: 512 512 3 3
conv5_3: 512 512 3 3
conv5_4: 512 512 3 3
fc6: 1 1 25088 4096
fc7: 1 1 4096 4096
fc8: 1 1 4096 1000
Setting up style layer          2       :       relu1_1
FD We fail here at target_i:div, which calls Tensor _div()..
THCudaCheck FAIL file=/tmp/luarocks_cutorch-scm-1-636/cutorch/lib/THC/generic/THCTensorMathPairwise.cu line=71 error=8 : invalid device function
/root/torch/install/bin/luajit: neural_style.lua:210: cuda runtime error (8) : invalid device function at /tmp/luarocks_cutorch-scm-1-636/cutorch/lib/THC/generic/THCTensorMathPairwise.cu:71
stack traceback:
        [C]: in function 'div'
        neural_style.lua:210: in function 'main'
        neural_style.lua:519: in main chunk
        [C]: in function 'dofile'
        /root/torch/install/lib/luarocks/rocks/trepl/scm-1/bin/th:145: in main chunk
        [C]: at 0x00405c20
[root@elementium neural-style]# nvidia-smi
Thu Jun 30 04:44:59 2016
+-----------------------------------------------------------------------------+
| NVIDIA-SMI 367.27                 Driver Version: 367.27                    |
|-------------------------------+----------------------+----------------------+
| GPU  Name        Persistence-M| Bus-Id        Disp.A | Volatile Uncorr. ECC |
| Fan  Temp  Perf  Pwr:Usage/Cap|         Memory-Usage | GPU-Util  Compute M. |
|===============================+======================+======================|
|   0  GeForce GTX 750 Ti  Off  | 0000:01:00.0      On |                  N/A |
| 80%   30C    P8     1W /  80W |    488MiB /  1999MiB |      0%      Default |
+-------------------------------+----------------------+----------------------+
|   1  GeForce GTX 750 Ti  Off  | 0000:06:00.0      On |                  N/A |
| 80%   31C    P8     1W /  52W |     56MiB /  2000MiB |      0%      Default |
+-------------------------------+----------------------+----------------------+
|   2  GeForce GTX 670     Off  | 0000:07:00.0     N/A |                  N/A |
| 80%   37C    P0    N/A /  N/A |     56MiB /  1998MiB |     N/A      Default |
+-------------------------------+----------------------+----------------------+

**Comment by fdimitri** [comment]
Reinstalling cunn through luarocks seems to have fixed the problem; apparently cunn detects which GPUs you have when compiling and only compiles code for that Compute Capability (at install time I only had the 750 Ti CC 5.0 cards in).

Reinstalling clearly showed 5.0 5.0 3.0; there are still some errors when setting up the style layer.

Setting up style layer          2       :       relu1_1
FD We fail here at target_i:div, which calls Tensor _div()..
Setting up style layer          7       :       relu2_1
FD We fail here at target_i:div, which calls Tensor _div()..
Setting up style layer          12      :       relu3_1
FD We fail here at target_i:div, which calls Tensor _div()..
Setting up style layer          21      :       relu4_1
FD We fail here at target_i:div, which calls Tensor _div()..
Setting up content layer        23      :       relu4_2
Setting up style layer          30      :       relu5_1
WARNING: Skipping content loss
FD We fail here at target_i:div, which calls Tensor _div()..

**Comment by fdimitri** [comment]
Hmm, this error now seems to show up even on my 750 Ti cards -- not sure if it has any impact.

**Comment by fdimitri** [comment]
Not an issue with neural-style, but perhaps it should be in the documentation that changing video cards may require:
```
#luarocks install cunn
```

Even if CC 3.0 code runs on a 5.0 card you should force the reinstall/recompile.

Going to complain to cunn dev about auto-detect nightmares :)

**Comment by crasse2** [comment]
thanks for the information ! as I'm planning to change my video cards, i'll keep that in mind
