### ISSUE TITLE
How to tune options to make it looks like prisma?

### ISSUE THREAD

**Issue by learnifysean** [jcjohnson/neural-style#278]
Hi Johnson!

I've read your implementation on fast neural style,

its good but after i've tried prisma app, the effects are different with your paper

result of prisma:
http://i.imgur.com/zrpLt4T.jpg

result of your paper:
http://i.imgur.com/uCJ9r6g.png

how to achieve the result that prisma did?

like preserve more feature of the original image and make style image more filter-ish

thanks!

**Comment by austingg** [comment]
@NorthFoxz  how about your style weight?  I think Prisma has done some alpha blending with the cotent images

**Comment by rayset** [comment]
What implementation did you use? Chainer fast neural style?

**Comment by NorthFoxz** [comment]
@rayset yes! but i cannot generate image with the same quality prisma provides, do you have any idea how to do that?

**Comment by Daddaaff** [comment]
I'm also experimenting with Chainer fast neural style. And I'm not near the quality of prisma ...

**Comment by Vladkryvoruchko** [comment]
Try https://github.com/DmitryUlyanov/texture_nets :) this project is related to prisma, but is a bit complicated with experiments
