### ISSUE TITLE
Generate multiple images from trained network?

### ISSUE THREAD

**Issue by drag0** [jcjohnson/neural-style#28]
Greetings, is there any way to save network that has been trained on an image and use it on different images multiple times without having it train itself over and over again?

**Comment by x1596357** [comment]
Isn't that what this repo doing?

**Comment by jcjohnson** [comment]
The network is pretrained on ImageNet; nothing in `neural_style.lua` modifies the weights from the pretrained network. The code takes a while to run because it runs an optimization problem over the output image, not because it is training a network.
