### ISSUE TITLE
Can I run the faster-RCNN Caffe model using this loadcaffe ?

### ISSUE THREAD

**Issue by bemoregt** [jcjohnson/neural-style#285]
Hi, Johnson.

Can I run the faster-RCNN Caffe model using this loadcaffe+torch method without Caffe?

fasterRCNN Caffe github is here:
https://github.com/rbgirshick/py-faster-rcnn

Thank you, in advances~

**Comment by jcjohnson** [comment]
Do you want to use py-faster-rcnn in neural-style or you just want to use it in Torch?

**Comment by bemoregt** [comment]
Thank you Answering.

I want to use fater-RCNN just in Torch, without Caffe.
Installation for using Caffe is so hard to me. --;
I have heard that loadcaffe method is not need to install Caffe... 

So, How can I making the "download_model.sh" file for Faster RCNN models?   

Thank you.

**Comment by jcjohnson** [comment]
loadcaffe is not a general solution for using Caffe models in Torch; it can only handle certain types of Caffe models, and py-faster-rcnn is not supported by loadcaffe.

For future reference, you should only open issues here if you have questions specific to neural-style; for more general questions about Torch you should use the Gitter chat (https://gitter.im/torch/torch7) or the Google group (https://groups.google.com/forum/#!forum/torch7).

**Comment by bemoregt** [comment]
OK, I see.
Thank you for your kind answer.
