### ISSUE TITLE
Dual GPU usage

### ISSUE THREAD

**Issue by vic8760** [jcjohnson/neural-style#288]
Im running a single instance of neural style with -GPU 0 with a 780ti, and i was wondering if i could run more instances of neural style on my remaining 2x cards ?

-gpu -1,-2,-3 doesnt work..

i get out of memory errors, but there is 0% utilization from my NVIDIA screen..thx

**Comment by 3DTOPO** [comment]
Yes, use  -GPU 1 for the second GPU. Negative numbers mean no GPU.

**Comment by vic8760** [comment]
ive tried -GPU 1, doesn't work, i have 2x 780ti's and a GTX 760 on idle

**Comment by 3DTOPO** [comment]
What is the full command you ran, and what exactly happens?

**Comment by vic8760** [comment]
Neural style is active right now on a 780ti 3GB. 

i run this for a second instance of neural style (The idle 760 gpu)

th neural_style.lua -style_image watch.jpg -content_image art.jpg -output_image derp.png -model_file models/nin_imagenet_conv.caffemodel -proto_file models/train_val.prototxt -num_iterations 500000 -content_layers relu0,relu1,relu2,relu3,relu12 -style_layers relu0,relu1,relu2,relu3,relu12 -optimizer adam -print_iter 1 -save_iter 1000 -tv_weight 0.0001 -style_scale 0.5 -backend cudnn -content_weight 5 -style_weight 350 -init random -learning_rate 4 -image_size 1800 -gpu 2

and i get this error

THCudaCheck FAIL file=/tmp/luarocks_cutorch-scm-1-487/cutorch/lib/THC/THCTensorRandom.cu line=20 error=2 : out of memory
/home/vic8760/torch/install/bin/luajit: /home/vic8760/torch/install/share/lua/5.1/trepl/init.lua:384: cuda runtime error (2) : out of memory at /tmp/luarocks_cutorch-scm-1-487/cutorch/lib/THC/THCTensorRandom.cu:20
stack traceback:
	[C]: in function 'error'
	/home/vic8760/torch/install/share/lua/5.1/trepl/init.lua:384: in function 'require'
	neural_style.lua:51: in function 'main'
	neural_style.lua:515: in main chunk
	[C]: in function 'dofile'
	...8760/torch/install/lib/luarocks/rocks/trepl/scm-1/bin/th:145: in main chunk
	[C]: at 0x00405d50

Sound like its conflicting with torch or something...im not sure

**Comment by jcjohnson** [comment]
The 760 only has 2GB of memory; it is running out of memory and dying.

**Comment by 3DTOPO** [comment]
The message is pretty clear - you are out of memory. How much VRAM does your 760 have?

**Comment by vic8760** [comment]
Here is a link of NVIDIA panel regarding my gpu's information
http://imgur.com/lgAZ4KG

**Comment by jcjohnson** [comment]
What is the output of `nvidia-smi`?

**Comment by vic8760** [comment]
Sun Jul 17 15:21:13 2016       
+------------------------------------------------------+                       
| NVIDIA-SMI 361.42     Driver Version: 361.42         |                       
|-------------------------------+----------------------+----------------------+
| GPU  Name        Persistence-M| Bus-Id        Disp.A | Volatile Uncorr. ECC |
| Fan  Temp  Perf  Pwr:Usage/Cap|         Memory-Usage | GPU-Util  Compute M. |
|===============================+======================+======================|
|   0  GeForce GTX 760...  Off  | 0000:01:00.0     N/A |                  N/A |
| 10%   35C    P8    N/A /  N/A |     81MiB /  3071MiB |     N/A      Default |
+-------------------------------+----------------------+----------------------+
|   1  GeForce GTX 780 Ti  Off  | 0000:03:00.0     N/A |                  N/A |
| 80%   81C    P0    N/A /  N/A |   2995MiB /  3071MiB |     N/A      Default |
+-------------------------------+----------------------+----------------------+
|   2  GeForce GTX 780 Ti  Off  | 0000:04:00.0     N/A |                  N/A |
| 56%   66C    P0    N/A /  N/A |   1092MiB /  3068MiB |     N/A      Default |
+-------------------------------+----------------------+----------------------+
                                                                               
+-----------------------------------------------------------------------------+
| Processes:                                                       GPU Memory |
|  GPU       PID  Type  Process name                               Usage      |
|=============================================================================|
|    0                  Not Supported                                         |
|    1                  Not Supported                                         |
|    2                  Not Supported                                         |
+-----------------------------------------------------------------------------+

**Comment by jcjohnson** [comment]
Looks like you have the 760 running the display, which takes 81MB of VRAM and that the 780 Ti in slot 1 is just on the edge of running out of memory; when you run the same settings on the 760 you are probably just barely running out of memory.

Your 760 should work, but you'll have to decrease the image size a bit. You should be able to run identical settings on both 780 Ti; you should be able to run on your other 780 Ti with the flag `-gpu 2`.

**Comment by vic8760** [comment]
ok, i will do that, thanks for taking your time on helping me, i really love this how program works, i just cant stop making art :D

Cheers!
