### ISSUE TITLE
error on running neural style - libcutorch.so

### ISSUE THREAD

**Issue by vibber** [jcjohnson/neural-style#298]
Hi I am trying to run the default

sudo th neural_style.lua -style_image picasso.jpg  -content_image miley.jpg

but I get this:

`~/torch/install/bin/luajit: ~/torch/install/share/lua/5.1/trepl/init.lua:384: ~/torch/install/share/lua/5.1/cutorch/init.lua:2: cannot load '~/torch/install/lib/lua/5.1/libcutorch.so'
stack traceback:
	[C]: in function 'error'
	~/torch/install/share/lua/5.1/trepl/init.lua:384: in function 'require'
	neural_style.lua:51: in function 'main'
	neural_style.lua:515: in main chunk
	[C]: in function 'dofile'
	~/torch/install/lib/luarocks/rocks/trepl/scm-1/bin/th:145: in main chunk
	[C]: at 0x010b419bd0
`

I think I have installed cutorch correctly but how do I check it?

**Comment by vibber** [comment]
I did a complete reinstall of everything which solved the problem.

**Comment by panfengli** [comment]
Try `sudo bash /torch/update.sh`
