### ISSUE TITLE
nvidia-smi fails

### ISSUE THREAD

**Issue by genekogan** [jcjohnson/neural-style#30]
running through the [installation instructions](https://github.com/jcjohnson/neural-style/blob/master/INSTALL.md) for an amazon g2.2xlarge instance ubuntu 14.04. everything seems to work okay but after running `sudo apt-get install cuda` and rebooting, the command `nvidia-smi` does not find the driver.

    $ nvidia-smi
    modprobe: ERROR: could not insert 'nvidia_346': Unknown symbol in module, or unknown parameter (see dmesg)
    NVIDIA-SMI has failed because it couldn't communicate with the NVIDIA driver. Make sure that the latest NVIDIA driver is installed and running.

i am guessing then that CUDA won't be working and i can't proceed?

**Comment by ryanpamplin** [comment]
Hi there. I found some prebaked AMIs that work excellently and save lots of time: http://blog.titocosta.com/post/110345699197/public-ec2-ami-with-torch-and-caffe-deep-learning. Here's a direct link to start this AMI on EC2 https://console.aws.amazon.com/ec2/v2/home?region=us-east-1#LaunchInstanceWizard:ami=ami-ffba7b94. Hope this helps you as much as it did me.

**Comment by genekogan** [comment]
yeah i am trying the ami route -- also found [this one](http://thecloudmarket.com/image/ami-6238470a--cuda-torch-distro).
thanks!
