### ISSUE TITLE
Any benchmarks for gtx 1060?

### ISSUE THREAD

**Issue by rayset** [jcjohnson/neural-style#303]
I saw the ones for 1080.

Anyone tried the 1060? What's its max resolution? How's the speed?

I'm really struggling to choose between the 1060 and 1070...if the difference is not to big I 'd get the 1060 since it's half the price.

**Comment by 3DTOPO** [comment]
A quick look at the specs and its not hard to see why it is half the price.

1. the 1060 has 52% the number of transistors of the 1070 and 1080.
2. It is rated at 58% TFLOPs as the 1070 (3.8 TFLOPs vs. 6.5 TFLOPs)
3. It has 75% the VRAM of the 1070, with 75% of the bandwidth. 

So it looks like the performance is a bit better than half of the 1070, but with less VRAM which will severely limit the resolution of the images it will be capable of rendering in a single pass.

**Comment by rayset** [comment]
The vram is 33% more, so I'll get 1.15x (square root of 1.33) bigger images in linear dimension.

I've read that deep style uses bandwidth more than tflops , so the 1060 seems to be around 75-80% of the 1080. Am I optimistic?

**Comment by 3DTOPO** [comment]
I don't think your math is quite right because the model will use a fixed amount of VRAM, then what is left over would be used for the image maps. So for instance, just making up numbers to illustrate a point, if the model used 5GB, that would leave 1GB for the image maps on the 1060 and 3GB on the 1070.

Also, the 1060 only has 66% the number of CUDA cores as the 1070, so, I think the TFLOPs are a good indication of that fact.

**Comment by rayset** [comment]
Thank you for the explanation. I think I'll try to save up.

Without considering ram dimension,the 980 seems better than the 1060,right?

**Comment by 3DTOPO** [comment]
I'm not certain, but from what I have read the 1070 performs better than the old Titan X, and the performance of the 980 is comparable to the old Titan X except it has less RAM. I also read that the new 1080 is roughly equal in performance to two 980tis.

**Comment by janisozaur** [comment]
1060 includea support for FP16 (albeit it's not a fast path), which may get added to neural style, I think there's an issue about that already. If you just want bigger images, that might be important.

**Comment by rayset** [comment]
Wow, so the titan x ,the only one with a fast implementation of this technology,will have 24 GB of ram for neural style.

Stunning.

Returning to 1060 if anyone can post how long does it take to do a max resolution image I'd be grateful.
