### ISSUE TITLE
neural_style.lua fails to start

### ISSUE THREAD

**Issue by tkoham** [jcjohnson/neural-style#323]
running

$  th neural_style -gpu -1 -print_iter 1 

produces:

stack traceback:
        [C]: in function 'dofile'
        .../Git/torch/install/lib/luarocks/rocks/trepl/scm-1/bin/th:145: in main chunk
        [C]: at 0x00405b80
and exits

**Comment by jcjohnson** [comment]
Can you post the full stack trace? This is not enough information to debug.

**Comment by htoyryla** [comment]
That indeed appears to be the full stack trace for "th neural_style -gpu -1 -print_iter 1" :)

Try 
```
 th neural_style.lua -gpu -1 -print_iter 1 
```
instead.

**Comment by tkoham** [comment]
Wow. Sleep deprivation impairs judgment more than you think sometimes. I forgot to append .lua. and boy do I feel silly for it. Thanks. issue closed.

**Comment by jcjohnson** [comment]
Don't worry, I didn't notice it either =)

Judicious use of tab-completion goes a long way toward preventing these sorts of mistakes.

**Comment by tkoham** [comment]
for sure. I'm working on adapting this to video content and being able to start the damned thing has gone a long way to making that a reality :^)

**Comment by tkoham** [comment]
Adding frame blending over time is hard. here's my first attempt if anypne's interested: 
https://www.youtube.com/watch?v=ER6A-CycHTY
