### ISSUE TITLE
Unable to get it to run with the normalized vgg net

### ISSUE THREAD

**Issue by anjishnu** [jcjohnson/neural-style#33]
I keep getting this strange gradient images
![attempt2_100](https://cloud.githubusercontent.com/assets/2019824/9783563/0b9ac2e0-575a-11e5-9867-aaa1c45211cf.jpg)

![attempt2_200](https://cloud.githubusercontent.com/assets/2019824/9783568/110d3406-575a-11e5-9071-94d6540f53a9.jpg)

![attempt2_300](https://cloud.githubusercontent.com/assets/2019824/9783584/1dd1d890-575a-11e5-9d2d-0ac8eb4d1b83.jpg)

![attempt2_400](https://cloud.githubusercontent.com/assets/2019824/9783587/25282414-575a-11e5-876e-85bf9e149b86.jpg)

Anyone else experienced this? Gradient explosion?

**Comment by jcjohnson** [comment]
Your TV regularization strength is too high.

**Comment by TobiasMR** [comment]
@jcjohnson which value did you use for the -tv_weight parameter? I experimented a bit with it, but it doens't get much better.

**Comment by jcjohnson** [comment]
I unfortunately don't remember exactly what range of TV weights values worked for the normalized network, except that the default of 1e-3 was way too high - probably 1e-5 or 1e-6 will work better. The TV regularization isn't super critical - you will get decent results even if you set it to 0, but the resulting images may have a bit of high frequency "screen door" noise.
