### ISSUE TITLE
out of memory

### ISSUE THREAD

**Issue by devpuck** [jcjohnson/neural-style#343]
hi,this is my problem 
root@li:~/neural-style# th neural_style.lua -style_image /home/li/test/xyy.jpeg  -content_image /home/li/test/zbl.jpg -output_image new.png  -gpu 0 -num_iterations 1000 -image_size 512
[libprotobuf WARNING google/protobuf/io/coded_stream.cc:537] Reading dangerously large protocol message.  If the message turns out to be larger than 1073741824 bytes, parsing will be halted for security reasons.  To increase the limit (or to disable these warnings), see CodedInputStream::SetTotalBytesLimit() in google/protobuf/io/coded_stream.h.
[libprotobuf WARNING google/protobuf/io/coded_stream.cc:78] The total number of bytes read was 574671192
Successfully loaded models/VGG_ILSVRC_19_layers.caffemodel
conv1_1: 64 3 3 3
conv1_2: 64 64 3 3
conv2_1: 128 64 3 3
conv2_2: 128 128 3 3
conv3_1: 256 128 3 3
conv3_2: 256 256 3 3
conv3_3: 256 256 3 3
conv3_4: 256 256 3 3
conv4_1: 512 256 3 3
conv4_2: 512 512 3 3
conv4_3: 512 512 3 3
conv4_4: 512 512 3 3
conv5_1: 512 512 3 3
conv5_2: 512 512 3 3
conv5_3: 512 512 3 3
conv5_4: 512 512 3 3
fc6: 1 1 25088 4096
fc7: 1 1 4096 4096
fc8: 1 1 4096 1000
Setting up style layer          2       :       relu1_1
Setting up style layer          7       :       relu2_1
Setting up style layer          12      :       relu3_1
Setting up style layer          21      :       relu4_1
THCudaCheck FAIL file=/tmp/luarocks_cutorch-scm-1-1172/cutorch/lib/THC/generic/THCStorage.cu line=40 error=2 : out of memory
/root/torch/install/bin/luajit: /root/torch/install/share/lua/5.1/nn/Container.lua:67:
In 19 module of nn.Sequential:
/root/torch/install/share/lua/5.1/nn/THNN.lua:110: cuda runtime error (2) : out of memory at /tmp/luarocks_cutorch-scm-1-1172/cutorch/lib/THC/generic/THCStorage.cu:40
stack traceback:
        [C]: in function 'v'
        /root/torch/install/share/lua/5.1/nn/THNN.lua:110: in function 'SpatialConvolutionMM_updateOutput'
        /root/torch/install/share/lua/5.1/nn/SpatialConvolution.lua:96: in function </root/torch/install/share/lua/5.1/nn/SpatialConvolution.lua:92>
        [C]: in function 'xpcall'
        /root/torch/install/share/lua/5.1/nn/Container.lua:63: in function 'rethrowErrors'
        /root/torch/install/share/lua/5.1/nn/Sequential.lua:44: in function 'forward'
        neural_style.lua:204: in function 'main'
        neural_style.lua:515: in main chunk
        [C]: in function 'dofile'
        /root/torch/install/lib/luarocks/rocks/trepl/scm-1/bin/th:145: in main chunk
        [C]: at 0x00405d50

WARNING: If you see a stack trace below, it doesn't point to the place where this error occurred. Please use only the one above.
stack traceback:
        [C]: in function 'error'
        /root/torch/install/share/lua/5.1/nn/Container.lua:67: in function 'rethrowErrors'
        /root/torch/install/share/lua/5.1/nn/Sequential.lua:44: in function 'forward'
        neural_style.lua:204: in function 'main'
        neural_style.lua:515: in main chunk
        [C]: in function 'dofile'
        /root/torch/install/lib/luarocks/rocks/trepl/scm-1/bin/th:145: in main chunk
        [C]: at 0x00405d50

**Comment by devpuck** [comment]
use -backend cudnn can solve this

**Comment by 128keaton** [comment]
@devpuck I cannot use cudnn sadly, I have a 2.0 compat GPU. I'm looking on eBay, but I can't really justify that kind of purchase for something more of a little side project
