### ISSUE TITLE
Pascal Titan X 12GB only uses 4GB with theano and also GPU-Z reports 4GB dedicated

### ISSUE THREAD

**Issue by brendanruff** [jcjohnson/neural-style#346]
I have noticed that with the recent TitanX Pascal 12GB VRAM (so nVidia claim anyway) both theano and GPU-Z only use up to 4GB, with GPU-Z reporting this as the dedicated (ie VRAM).

Is this the case, ie Titan X only has 4GB of useful VRAM memory for theano to use ? If not please anyone let me know if there is a way to configure to get full use of the 12GB.

thanks
Brendan

**Comment by htoyryla** [comment]
Neural-style does not use theano, so maybe you meant to post this elsewhere?

**Comment by brendanruff** [comment]
oops sorry ! No idea how I put this on this thread !
