### ISSUE TITLE
precomputing styles of input picture

### ISSUE THREAD

**Issue by daeheehan** [jcjohnson/neural-style#35]
hi, actually I'm not familiar in deep learning, but it occurs to me,

There are two input images for this algorithm. 
(a) a picture to extract style 
(b) a picture of which we're going to change the style

can we pre-train the network only with image (a), so that we can speed-up getting the result with (b)?

as far as I understood, it seems impossible since the function we're going to optimize is dependent on both images (a) and (b), not only (a).

or is there any good ways to accelerate the whole operation?

**Comment by jcjohnson** [comment]
That sounds like an open research problem :)

However I do agree that this would be very useful.
