### ISSUE TITLE
Question: Running on AWS

### ISSUE THREAD

**Issue by bestguy** [jcjohnson/neural-style#37]
Would be awesome if anyone could document how to run on AWS with CUDA.

**Comment by dendisuhubdy** [comment]
That would be also a good idea!

**Comment by dasantonym** [comment]
there are quite a few ami's that already have cuda installed and if you want to install it yourself just http://lmgtfy.com/?q=cuda+amazon+aws (sorry, i just had to)

**Comment by bestguy** [comment]
Thanks, I suppose I meant all the other deps as well - am new to Lua, and even installing on my local Mac was non trivial :-)

**Comment by bestguy** [comment]
Will close and update if I write up instructions.
