### ISSUE TITLE
Cudnn backend requires libcudnn.so5 / libcudnn.so.5

### ISSUE THREAD

**Issue by korelace** [jcjohnson/neural-style#378]
So i installed CUDA 7.0 and cuDNN 4 as in the insall.md. CUDA is working and "luarocks install cudnn" seems good, but when i try "th neural_style.lua -gpu 0 -backend cudnn" it prints errors : 

`/home/notrobot/torch/install/bin/luajit: /home/notrobot/torch/install/share/lua/5.1/trepl/init.lua:389: /home/notrobot/torch/install/share/lua/5.1/trepl/init.lua:389: /home/notrobot/torch/install/share/lua/5.1/cudnn/ffi.lua:1603: 'libcudnn (R5) not found in library path.
Please install CuDNN from https://developer.nvidia.com/cuDNN
Then make sure files named as libcudnn.so.5 or libcudnn.5.dylib are placed in
your library load path (for example /usr/local/lib , or manually add a path to LD_LIBRARY_PATH)`

`Alternatively, set the path to libcudnn.so.5 or libcudnn.5.dylib
to the environment variable CUDNN_PATH and rerun torch.
For example: export CUDNN_PATH = "/usr/local/cuda/lib64/libcudnn.so.5"`

`stack traceback:
	[C]: in function 'error'
	/home/notrobot/torch/install/share/lua/5.1/trepl/init.lua:389: in function 'require'
	neural_style.lua:350: in function 'setup_gpu'
	neural_style.lua:53: in function 'main'
	neural_style.lua:601: in main chunk
	[C]: in function 'dofile'
	...obot/torch/install/lib/luarocks/rocks/trepl/scm-1/bin/th:150: in main chunk
	[C]: at 0x00406670`

Thanks for every help.

**Comment by MrZoidberg** [comment]
Try to follow the answer [here](http://askubuntu.com/questions/767269/how-can-i-install-cudnn-on-ubuntu-16-04/767270#767270). It helped me the last time I've installed cuDNN.

Also why are you using old version of CUDA and cuDNN? The latest versions are CUDA 8.0 and cuDNN 5.1.

**Comment by htoyryla** [comment]
Neural-style installation instructions still refer to cuda7.0 and cudnn4.0, probably just because nobody has updated them. I am using 8.0 and 5.1 and in fact the new cards like 1080 will not work on 7.5 or older.

**Comment by MrZoidberg** [comment]
@htoyryla yep, I'm using 1080 and it doesn't work on old drivers. I think someone needs to make PR with the installation guide changes )
