### ISSUE TITLE
/torch/install/bin/luajit: C++ exception

### ISSUE THREAD

**Issue by drag0** [jcjohnson/neural-style#38]
Program runs smoothly on my home machine, but when I try to run it without GPU on DigitalOcean instance I get this error:
/root/torch/install/bin/luajit: C++ exception

What could be the problem? I'm using it excatly the same as I'm using it on my local machine.

**Comment by jcjohnson** [comment]
Did you remember to pass `-gpu -1` to run in CPU mode?

**Comment by drag0** [comment]
@jcjohnson - I'm using -gpu -1 already. 
I tried removing torch, reinstalling it completely with luajit etc. but it didn't help.

**Comment by jcjohnson** [comment]
I don't suppose you're lucky enough to get a stack trace?

**Comment by drag0** [comment]
Nope, nothing, just that 1 line.
I'm testing it on instance with only 512 MB RAM and 1 CPU, could it be something about that? 
I passed -image_size 30 to the script because I just wanted to test it on weak instance before I turn on expensive instances with 30 cores.

**Comment by jcjohnson** [comment]
Wow - that's a very tiny amount of memory.

You are probably running out of memory when loading the VGG-19 model, which is 549MB. You can try using the normalized VGG network instead - it doesn't contain the fully-connected layers, so it is only 77MB. Try running with the following flag:

`-model_file  models/vgg_normalised.caffemodel`

You probably won't get pretty results with this model using default hyperparameters, but at least you should be able to run the code on a tiny instance.

**Comment by drag0** [comment]
@jcjohnson 
Managed to run it now with normalised model but the process is being killed.
This is the output:

Successfully loaded models/vgg_normalised.caffemodel
conv1_1: 64 3 3 3
conv1_2: 64 64 3 3
conv2_1: 128 64 3 3
conv2_2: 128 128 3 3
conv3_1: 256 128 3 3
conv3_2: 256 256 3 3
conv3_3: 256 256 3 3
conv3_4: 256 256 3 3
conv4_1: 512 256 3 3
conv4_2: 512 512 3 3
conv4_3: 512 512 3 3
conv4_4: 512 512 3 3
conv5_1: 512 512 3 3
conv5_2: 512 512 3 3
conv5_3: 512 512 3 3
conv5_4: 512 512 3 3
Killed

I'll try to run it on stronger instance and report here with results.

**Comment by jcjohnson** [comment]
You are probably still running out of memory; you can further reduce memory usage by using ADAM rather than L-BFGS for optimization; try running with the flag `-optimizer adam`.

**Comment by drag0** [comment]
Yep, it works that way. Image is completely gray but I'll play with -tv_weight parameter to get better results. Thanks again!
