### ISSUE TITLE
Trouble in preprocess image

### ISSUE THREAD

**Issue by SSeanHsu** [jcjohnson/neural-style#381]
The code in `function preprocess(img)`:
`local mean_pixel = torch.DoubleTensor({103.939, 116.779, 123.68})`

Are there any reasons why we should use `{103.939, 116.779, 123.68}` instead of computing the mean pixel of content image?

**Comment by htoyryla** [comment]
The given mean comes from the authors of VGG19 and originally derives from the training image set. In other words it is the total mean of the images that the model has seen during training.

**Comment by SSeanHsu** [comment]
Wow, thanks for your quick reply. I am new in this domain, and I still want to know where did you get that? How did you know the mean? I didn't find that in the VGG paper(https://arxiv.org/abs/1409.1556)

**Comment by htoyryla** [comment]
See here https://gist.github.com/ksimonyan/3785162f95cd2d5fee77#file-readme-md .

**Comment by SSeanHsu** [comment]
@htoyryla Got it, thanks a lot.
