### ISSUE TITLE
Hardware Requirements and Benchmarking

### ISSUE THREAD

**Issue by DavidFreebairn** [jcjohnson/neural-style#386]
Hi Justin and co.,

I am looking to use your neural style git method to apply a painterly look to a 30 min video.  At 25 fps, this means that I need a setup to produce 45,000 frames total.  I am struggling to understand exactly what kind of hardware setup I need to achieve this within a reasonable time-frame (reasonable is of course highly subjective).  

According to this blog on the nVidia website: https://blogs.nvidia.com/blog/2016/05/25/deep-learning-paints-videos/ and my own calculations, a Titan X rendering at 10 minutes a frame would mean it would take 312.5 days to complete a 30-min video!  Have I got this right?

I'm going to post a mess of questions here, answers to any will be greatly appreciated:

Can anyone tell me if this can be greatly sped up depending on set-up/ resolution of the individual frames comprising the resultant video?  

Any advice with regards to buying, minimum required setups, example benchmark setups with times to complete... Would a gtx 1080 with i7, a clean ubuntu install with say 6-8 GB dedicated RAM suffice? 

Can what I'm trying to achieve even be realised at this current time or is the technology not far enough along yet?

Is this only practical with an uber-expensive 4xTitan X setup?

Is there any chance the setup I have at present (i5 and gtx 970) could do this? It does have Cuda cores after all ;-)

Any help will be greatly appreciated. I haven't found any other similar discussions regarding what is TRULY required to set up this process for video rendering with sample render time calculations.

**Comment by htoyryla** [comment]
For style transfer of a large number of images, something like https://github.com/jcjohnson/fast-neural-style or https://github.com/DmitryUlyanov/texture_nets is much faster. Once you have trained a model for the specific style, you should be able to convert several images per second (may require some coding to do bulk transfer. It may take some effort also to get the model right in the first place.

However, simply converting frames may not produce smooth video. For that there appear to be special solutions, employing methods like optical flow, but I don't have experience on that area.

**Comment by DavidFreebairn** [comment]
Thanks for your response @htoyryla greatly appreciated.  I was unaware of fast-neural-style so will give it a bash in cpu and gpu modes to test. Thanks again!
