### ISSUE TITLE
segmentation fault on vm

### ISSUE THREAD

**Issue by recycli** [jcjohnson/neural-style#39]
Installed neural-style on ubuntu 14.04 LTS virtual machine:
Memory : 3.9 GiB
Processor : i5-3210M CPU @ 2.50GHz x 4

while installing torch7, `./install.sh` didn't work so I followed the instructions on https://github.com/torch/torch7/issues/191, and it worked fine.

However, `th neural_style.lua -gpu -1` gives me an error:
```
[libprotobuf WARNING google/protobuf/io/coded_stream.cc:505] Reading dangerously large protocol message.  If the message turns out to be larger than 1073741824 bytes, parsing will be halted for security reasons.  To increase the limit (or to disable these warnings), see CodedInputStream::SetTotalBytesLimit() in google/protobuf/io/coded_stream.h.
[libprotobuf WARNING google/protobuf/io/coded_stream.cc:78] The total number of bytes read was 574671192
Successfully loaded models/VGG_ILSVRC_19_layers.caffemodel
conv1_1: 64 3 3 3
conv1_2: 64 64 3 3
conv2_1: 128 64 3 3
conv2_2: 128 128 3 3
conv3_1: 256 128 3 3
conv3_2: 256 256 3 3
conv3_3: 256 256 3 3
conv3_4: 256 256 3 3
conv4_1: 512 256 3 3
conv4_2: 512 512 3 3
conv4_3: 512 512 3 3
conv4_4: 512 512 3 3
conv5_1: 512 512 3 3
conv5_2: 512 512 3 3
conv5_3: 512 512 3 3
conv5_4: 512 512 3 3
fc6: 1 1 25088 4096
Segmentation fault (core dumped)
```

`gdb test core` gives this message:
```
warning: core file may not match specified executable file.
[New LWP 2807]
Core was generated by `/home/recycli/torch/install/bin/luajit -e package.path="/home/recycli/.luarocks'.
Program terminated with signal SIGSEGV, Segmentation fault.
#0  0x08053dd9 in ?? ()
```

system monitor while executing `neural_style.lua` :
![image](https://cloud.githubusercontent.com/assets/6560872/9829804/d9363df0-594f-11e5-8f36-4b5dac826d86.png)

What could be the problem? Still same thing happens after allocating 5GiB of memory to the virtual machine.

**Comment by drag0** [comment]
Try passing parameter -image_size 150 and check if it works. 4GB of RAM is barely enough for images around 500px. Also, after that you can try using -optimizer adam and vgg_normalised network for more memory reduction.

**Comment by recycli** [comment]
Finally found the reason: virtual machine was **32-bit** ubuntu.
Upgraded it to 64-bit and now it works well. Thanks for help, drag0.

**Comment by jcjohnson** [comment]
Wow, nice catch!
