### ISSUE TITLE
Hi this isn't an issue, just a question

### ISSUE THREAD

**Issue by tindoductran** [jcjohnson/neural-style#41]
I have never worked with Lua or GitHub before.
I just ran into your README file and extremely interested in this after seeing results from images.
From the README I am guessing you've written instructions for linux.
I have a Windows 10 laptop.
Can you instruct me (step-by-step) or point me in the right direction to tutorials on how to set this up on my machine so i can run on images.
Thanks.
So far I just got Lua for Windows installed an unsure what to do next.

**Comment by jcjohnson** [comment]
Unfortunately torch does not officially support Windows and probably won't in the foreseeable future; see https://github.com/torch/torch7/issues/150. It seems that some brave souls have gotten torch to run on Windows but it looks pretty difficult; there is some information here:

https://groups.google.com/forum/#!searchin/torch7/windows/torch7/A5XUU4u9Tjw/yvSJCBuLj4oJ

Honestly your best bet is probably either to dual-boot or run a VM with some flavor of Linux.

**Comment by tindoductran** [comment]
thank you.

**Comment by tindoductran** [comment]
Okay I first I tried Fedora but it didn't work for me so I tried Ubuntu and it worked.
Now I am in Ubuntu (dual booted).
What steps should i perform next... I am very inexperienced with Linux.
I can do basic things like opening the browser and can open terminal window.
Thanks in advance.

**Comment by tindoductran** [comment]
or if you could tell me what i should search for in short phrases so i could start googling on what to do in steps in order to run your code. That would be great. thanks again.

**Comment by jcjohnson** [comment]
Try the installation instructions here:

https://github.com/jcjohnson/neural-style/blob/master/INSTALL.md

**Comment by tindoductran** [comment]
sweet thanks.

**Comment by tindoductran** [comment]
I tried running it and after 40 minutes it still hangs on the "Running optimization with L-BFGS" line
is this supposed to happen..should i wait longer? I have 4G DDR3 Memory.

tran@tran-ubuntu:~/neural-style$ th neural_style.lua -gpu -1 -print_iter -1 -style_image ../Desktop/japanese.jpg -content_image ../Desktop/index.jpeg 
[libprotobuf WARNING google/protobuf/io/coded_stream.cc:537] Reading dangerously large protocol message.  If the message turns out to be larger than 1073741824 bytes, parsing will be halted for security reasons.  To increase the limit (or to disable these warnings), see CodedInputStream::SetTotalBytesLimit() in google/protobuf/io/coded_stream.h.
[libprotobuf WARNING google/protobuf/io/coded_stream.cc:78] The total number of bytes read was 574671192
Successfully loaded models/VGG_ILSVRC_19_layers.caffemodel
conv1_1: 64 3 3 3
conv1_2: 64 64 3 3
conv2_1: 128 64 3 3
conv2_2: 128 128 3 3
conv3_1: 256 128 3 3
conv3_2: 256 256 3 3
conv3_3: 256 256 3 3
conv3_4: 256 256 3 3
conv4_1: 512 256 3 3
conv4_2: 512 512 3 3
conv4_3: 512 512 3 3
conv4_4: 512 512 3 3
conv5_1: 512 512 3 3
conv5_2: 512 512 3 3
conv5_3: 512 512 3 3
conv5_4: 512 512 3 3
fc6: 1 1 25088 4096
fc7: 1 1 4096 4096
fc8: 1 1 4096 1000
WARNING: Skipping content loss	
Running optimization with L-BFGS

**Comment by jcjohnson** [comment]
My guess is that you are spilling over your physical memory and swapping to disk, making it very slow as discussed in https://github.com/jcjohnson/neural-style/issues/21. Try reducing the image size: `-image_size 128` and see if it runs faster.

**Comment by tindoductran** [comment]
just wondering if you know that your code/project is used on this site (they credited you at bottom).
https://www.instapainting.com/ai-painter.

**Comment by jcjohnson** [comment]
Yeah I saw that - it's a cool application!
