### ISSUE TITLE
Question: Are the parameters of VGG updated during image synthesis?

### ISSUE THREAD

**Issue by TheIllusion** [jcjohnson/neural-style#414]
I've understand that the synthesized output image is generated by minimizing style and content loss. 

During iterations, are the parameters of VGG also updated?

As far as I understand, only the input noise image is the only parameter that will be updated. 
And the parameters of VGG is fixed during the whole process.

Is my understanding right?

Thanks for your great work.

**Comment by htoyryla** [comment]
Parameters of VGG are fixed, only the image changes during the iterations.

**Comment by TheIllusion** [comment]
Thanks for your confirmation.
Now everything is clear in my mind.
