### ISSUE TITLE
<optim.lbfgs> 	reached max number of iterations

### ISSUE THREAD

**Issue by michaelgiba** [jcjohnson/neural-style#42]
![screen shot 2015-09-14 at 7 13 20 pm](https://cloud.githubusercontent.com/assets/6708065/9864925/b68c1880-5b14-11e5-8b9b-43005cca6a70.png)

**Comment by jcjohnson** [comment]
It only ran for one iteration because you passed the flag `num_iterations 1`.

**Comment by michaelgiba** [comment]
Oh my gosh I thought that was an error and didn't even check if the image came out.....

**Comment by michaelgiba** [comment]
Foolish! Sorry about that

**Comment by jcjohnson** [comment]
No problem - it happens to everyone from time to time ;)
