### ISSUE TITLE
cannot open neural_style.lua: No such file or directory

### ISSUE THREAD

**Issue by wungky** [jcjohnson/neural-style#422]
Dear neural-styles enthusiasts:

# **PREFACE**
This is a follow up to my previous question. I am still quite new to this, I ask for your patience.

I'm dual booting Ubuntu 16.04.03 LTS with Windows 10 on a 1TB HD with 2 x Nvidia Gtx1050 in the hopes of generating neural-style images. So far, I am able to run the basic script with no problems:

`th neural_style.lua -style_image /home/mike/neural-style/examples/inputs/brad_pitt.jpg -content_image /home/mike/neural-style/examples/inputs/picasso_selfport1907.jpg`

However, as I have two GPUs, I tried modifying the example .sh multigpu script provided in the /examples/multigpu_scripts/starry.stanford.sh folder called starry_stanford

# **ERRORS**
Upon navigating to the root folder and trying the code:

> mike@brain:~/neural-style/examples/multigpu_scripts$ sh starry_stanford.sh

I am returned with the error:
/home/mike/torch/install/bin/luajit: cannot open neural_style.lua: No such file or directory
stack traceback:
	[C]: in function 'dofile'
	...mike/torch/install/lib/luarocks/rocks/trepl/scm-1/bin/th:150: in main chunk
	[C]: at 0x00405d50
/home/mike/torch/install/bin/luajit: cannot open neural_style.lua: No such file or directory
stack traceback:
	[C]: in function 'dofile'
	...mike/torch/install/lib/luarocks/rocks/trepl/scm-1/bin/th:150: in main chunk
	[C]: at 0x00405d50
/home/mike/torch/install/bin/luajit: cannot open neural_style.lua: No such file or directory
stack traceback:
	[C]: in function 'dofile'
	...mike/torch/install/lib/luarocks/rocks/trepl/scm-1/bin/th:150: in main chunk
	[C]: at 0x00405d50
/home/mike/torch/install/bin/luajit: cannot open neural_style.lua: No such file or directory
stack traceback:
	[C]: in function 'dofile'
	...mike/torch/install/lib/luarocks/rocks/trepl/scm-1/bin/th:150: in main chunk
	[C]: at 0x00405d50
/home/mike/torch/install/bin/luajit: cannot open neural_style.lua: No such file or directory
stack traceback:
	[C]: in function 'dofile'
	...mike/torch/install/lib/luarocks/rocks/trepl/scm-1/bin/th:150: in main chunk
	[C]: at 0x00405d50

After digging around on this repository, I've also tried navigating to ~/neural-styles instead of ~/neural-style/examples/multigpu_scripts:

> mike@brain:~/neural-style$ sh starry_stanford.sh

I am returned with the error:

> sh: 0: Can't open starry_stanford.sh

# **CONCLUSION**
I was definitely able to run this script in the past few days. I have made no code or software changes to my system. However, I am unable to run the script which leads me to believe that I am either not in the correct directory and this is a simple, fixable error. 

Could anyone illuminate why I could be experiencing this problem?

**Comment by htoyryla** [comment]
You should run the script from the main directory (neural-style) where the neural_style.lua is located, not from the directory where the script is, using a command like 
```
sh example/multigpu_scripts/starry_stanford.sh
```

**Comment by wungky** [comment]
Dear htoyryla,

Thank you for your speedy response! You are a sir and a scholar.

IT WORKS!
