### ISSUE TITLE
Install postgres-xl

### ISSUE THREAD

**Issue by adnanhamdussalam** [jcjohnson/neural-style#430]
Hi,

I am receving below error while installing the postgres-xl:

[root@A0310TPGSQLSRV01 ~]# cd /U01/PostgreSQL/9.6/media/postgres-xl-9.5r1.6/postgres-xl-9.5r1.6/contrib/pgxc_ctl
[root@A0310TPGSQLSRV01 pgxc_ctl]# make install
gcc -DPGXC -DXCP -Wall -Wmissing-prototypes -Wpointer-arith -Wdeclaration-after-statement -Wendif-labels -Wmissing-format-attribute -Wformat-security -fno-strict-aliasing -fwrapv -fexcess-precision=standard -O2 pgxc_ctl_bash.o bash_handler.o config.o pgxc_ctl.o variables.o pgxc_ctl_log.o do_command.o utils.o do_shell.o gtm_cmd.o coord_cmd.o datanode_cmd.o gtm_util.o mcxt.o monitor.o -L../../src/common -lpgcommon -L../../src/port -lpgport -L../../src/interfaces/libpq -lpq -lpthread    ../../src/gtm/common/assert.o ../../src/gtm/client/libgtmclient.a ../../src/gtm/common/gtm_serialize.o -L../../src/port -L../../src/common -Wl,--as-needed -Wl,-rpath,'/usr/local/pgsql/lib',--enable-new-dtags  -lpgcommon -lpgport -lz -lrt -lcrypt -ldl -lm  -o pgxc_ctl
do_command.o: In function `do_command':
do_command.c:(.text+0x73d1): undefined reference to `readline'
do_command.c:(.text+0x742c): undefined reference to `add_history'
do_command.c:(.text+0x7445): undefined reference to `write_history'
do_command.c:(.text+0x7487): undefined reference to `read_history'
collect2: error: ld returned 1 exit status
make: *** [pgxc_ctl] Error 1
[root@A0310TPGSQLSRV01 pgxc_ctl]# 

Regards,

Adnan

**Comment by htoyryla** [comment]
@adnanhamdussalam 
You probably posted this to the wrong project. Postgres has nothing to do with neural-style.

**Comment by adnanhamdussalam** [comment]
Hi  htoyryla,

Right Thank you for guiding me .

Regards,

Adnan
