### ISSUE TITLE
Hey, sorry to bother you guys again... Reinstalling stuff and hit a weird error code

### ISSUE THREAD

**Issue by jcklpe** [jcjohnson/neural-style#452]
I'm finally making good on my promise to make a tutorial for artists on how to use neural style, but.... well I'm reinstalling and I ran into this error and was wondering what I might doing wrong? Following the ubuntu install instructions. 

![image](https://user-images.githubusercontent.com/9451726/37693527-53c50204-2c8e-11e8-9001-7c7b7be1fb87.png)

**Comment by 3DTOPO** [comment]
It appears that you are building cu-torch but it cannot find the required CUDA toolkit. Have you installed CUDA?

**Comment by 3DTOPO** [comment]
(CUDA isn't required for neural-style, but it is required if you want it to run on the GPU and is required if you are installing cu-torch)

**Comment by jcklpe** [comment]
I did attempt it. Maybe it didn't install properly?

Okay now I'm thinking about it the instructions were for Ubuntu 14 and I'm
using Ubuntu 16. But I've seen people in the forums and issues logs using
16 so I guess I hoped it would work... What do I need to change in the
script I run in cli in order to get Cuda for 16?   I'm sorry to be so
useless on this. Like I've said before I'm an artist and designer figuring
this stuff out extremely piecemeal.

**Comment by 3DTOPO** [comment]
Ubuntu 16 is fine - thats what I run. What version of CUDA did you install? How did you install it?

**Comment by ProGamerGov** [comment]
There may be some useful information in this issue: https://github.com/jcjohnson/neural-style/issues/443, but I think it was related to OSX. But I successfully got Cuda 9 to work with Ubuntu 16.04.

**Comment by jcklpe** [comment]
@3DTOPO I basically just copy pasted stuff from this guide and put it in the command line: https://github.com/jcjohnson/neural-style/blob/master/INSTALL.md

**Comment by jcklpe** [comment]
`# For Ubuntu 14.10
wget http://developer.download.nvidia.com/compute/cuda/7_0/Prod/local_installers/rpmdeb/cuda-repo-ubuntu1410-7-0-local_7.0-28_amd64.deb
sudo dpkg -i cuda-repo-ubuntu1410-7-0-local_7.0-28_amd64.deb`

`sudo apt-get update
sudo apt-get install cuda`

**Comment by 3DTOPO** [comment]
Hmm - those instructions say they are for installing CUDA on Ubuntu 14. Google how to install CUDA 8 on Ubuntu 16. CUDA 9 might work for you, but I had problems with it on my machine.

**Comment by jcklpe** [comment]
Ah okay cool. Thanks! I had a feeling that wasn't the right thing for me to do but wasn't sure. Thanks!

**Comment by jcklpe** [comment]
More problems. I feel like I'm probably overlooking something obvious. I wish I hadn't installed 16, because I have a bad feeling that is what is causing some of these issues. And I want this tutorial to be as easy as possible to follow but the way I'm doing things looks like it's actually going to be pretty janky. 

Here's the read out I'm getting :/

```
cd neural-style
david@TheWiz:~/neural-style$ th neural_style.lua -gpu 0 -backend cudnn
/home/david/torch/install/bin/luajit: /home/david/torch/install/share/lua/5.1/trepl/init.lua:389: /home/david/torch/install/share/lua/5.1/trepl/init.lua:389: /home/david/torch/install/share/lua/5.1/cudnn/ffi.lua:1603: 'libcudnn (R5) not found in library path.
Please install CuDNN from https://developer.nvidia.com/cuDNN
Then make sure files named as libcudnn.so.5 or libcudnn.5.dylib are placed in
your library load path (for example /usr/local/lib , or manually add a path to LD_LIBRARY_PATH)

Alternatively, set the path to libcudnn.so.5 or libcudnn.5.dylib
to the environment variable CUDNN_PATH and rerun torch.
For example: export CUDNN_PATH="/usr/local/cuda/lib64/libcudnn.so.5"

stack traceback:
        [C]: in function 'error'
        /home/david/torch/install/share/lua/5.1/trepl/init.lua:389: in function 'require'
        neural_style.lua:350: in function 'setup_gpu'
        neural_style.lua:53: in function 'main'
        neural_style.lua:601: in main chunk
        [C]: in function 'dofile'
        ...avid/torch/install/lib/luarocks/rocks/trepl/scm-1/bin/th:150: in main chunk
        [C]: at 0x00405d50
david@TheWiz:~/neural-style$ th neural_style.lua -gpu 0 -print_iter 1
Couldn't load models/VGG_ILSVRC_19_layers.caffemodel
/home/david/torch/install/bin/luajit: neural_style.lua:57: attempt to index a nil value
stack traceback:
        neural_style.lua:57: in function 'main'
        neural_style.lua:601: in main chunk
        [C]: in function 'dofile'
        ...avid/torch/install/lib/luarocks/rocks/trepl/scm-1/bin/th:150: in main chunk
        [C]: at 0x00405d50
```

**Comment by jcklpe** [comment]
Oh I think I see the problem. I need at least version 5 I guess

**Comment by jcklpe** [comment]
Okay I put version 5 of cudnn and it still doesn't seem to be working. 

![image](https://user-images.githubusercontent.com/9451726/37810484-4b31ce98-2e22-11e8-9ada-5af731f6e617.png)

**Comment by 3DTOPO** [comment]
If you installed CUDA 8, you will have to install cuDNN 5.1. 5.0 doesn't support CUDA 8.

Think you're almost there now though!

**Comment by jcklpe** [comment]
I install cuda 9 because I couldn't find the archived page and I figured it wouldn't make too big of a difference.

**Comment by 3DTOPO** [comment]
Hmm, I don't think CUDA 9 supports cuDNN 5.x (thought I recommend 8). 

Anyhow, I guess your left with two choices: (1) not use cuDNN acceleration or (2) remove CUDA 9, install CUDA 8, rebuild Torch and install cuDNN 5.1.

**Comment by jcklpe** [comment]
CUDA doesn't support 5.x? Does it support a different version of cudnn?

**Comment by 3DTOPO** [comment]
CUDA 9 does not support cuDNN 5.x. cuDNN 5.x is the only version supported by neural-style.

On the cuDNN download page, it says what versions of CUDA the download supports...

**Comment by jcklpe** [comment]
Yeah, a lot of them said supports X and up so I assumed there was some level of forward compatibility. 

I just tried a download of 5.1 but that's not working either. So I'm just going to uninstall and install 8

only problem is that now it's not letting me get apt-get update saying I don't have permissions to remove caches

**Comment by jcklpe** [comment]
I'm an idiot. I refreshed the console and forgot that sudo logged out

**Comment by 3DTOPO** [comment]
Can happen to the best of us. ;)

Here are instructions how to completely purge 9: https://askubuntu.com/questions/959835/how-to-remove-cuda-9-0-and-install-cuda-8-0-instead

**Comment by jcklpe** [comment]
Okay I've removed it and installed 8 and I ran the luarocks cutorch command again. 

Last time it did something similar where it kept repeating variations of this line while running 


```
CMake Warning at /usr/share/cmake-3.5/Modules/FindCUDA/make2cmake.cmake:65 (message):
   Removing non-existent dependency file: generic/THCTensorIndex.h
```


Which makes me worry it's not working...

**Comment by 3DTOPO** [comment]
I think its OK - its a warning not an error. Does the build complete?

**Comment by jcklpe** [comment]
Yup. just finished the second luarocks script. 

Then I got this:
```

david@TheWiz:~$ cd neural-style
david@TheWiz:~/neural-style$ th neural_style.lua -gpu 0 -print_iter 1
Couldn't load models/VGG_ILSVRC_19_layers.caffemodel
/home/david/torch/install/bin/luajit: neural_style.lua:57: attempt to index a nil value
stack traceback:
        neural_style.lua:57: in function 'main'
        neural_style.lua:601: in main chunk
        [C]: in function 'dofile'
        ...avid/torch/install/lib/luarocks/rocks/trepl/scm-1/bin/th:150: in main chunk
        [C]: at 0x00405d50
```

**Comment by 3DTOPO** [comment]
Did you download the VGG model? It should be in the models folder in the neural-style folder.

**Comment by jcklpe** [comment]
Bingo. That was it. I did that earlier but it must have errorred when I wasn't looking. It works with CPU now. Doesn't work with GPU. I'm trying to redo the cutorch stuff again and maybe that will fix it

**Comment by 3DTOPO** [comment]
What happens if you run `nvidia-smi`?

**Comment by jcklpe** [comment]
```
+-----------------------------------------------------------------------------+
| NVIDIA-SMI 390.30                 Driver Version: 390.30                    |
|-------------------------------+----------------------+----------------------+
| GPU  Name        Persistence-M| Bus-Id        Disp.A | Volatile Uncorr. ECC |
| Fan  Temp  Perf  Pwr:Usage/Cap|         Memory-Usage | GPU-Util  Compute M. |
|===============================+======================+======================|
|   0  GeForce GTX 970     Off  | 00000000:01:00.0  On |                  N/A |
|  0%   39C    P0    50W / 170W |    303MiB /  4038MiB |      2%      Default |
+-------------------------------+----------------------+----------------------+
                                                                               
+-----------------------------------------------------------------------------+
| Processes:                                                       GPU Memory |
|  GPU       PID   Type   Process name                             Usage      |
|=============================================================================|
|    0      1128      G   /usr/lib/xorg/Xorg                           127MiB |
|    0      1857      G   compiz                                       101MiB |
|    0      3199      G   ...-token=5BA11C9F2E7512A85C197369150516FF    23MiB |
|    0     25754      G   cool-retro-term                               44MiB |
+-----------------------------------------------------------------------------+

```

**Comment by jcklpe** [comment]
BINGO! It works! I'll be sure to report back and close this when I finish the article. And if anybody was interested in taking a look at a draft of it before I post it just send me an email at david@jackalope.tech  Thank you guys! (I'll also be sure to credit ya'll in the article so if you want me to link any websites or social media things just let me know :)  )

**Comment by 3DTOPO** [comment]
Nice, congrats!

I was going to say the output of `nvidia-smi` means the driver is working.

**Comment by jcklpe** [comment]
Oookkay. I feel kind of dumb but I don't know what I'm doing wrong. 

I got everything installed. Tested. It's working. So I write up a shell script to automate a bunch of image processing and it doesn't seem to be working.... I've tried running it in hyperterm and in the default terminal. I've tried running it as a shell script and copying and pasting it into the terminal. I've tried it as a super long single line script and I've tried it as a multiline script. Not sure what's going on. Any clues?

`content=asiangirl && neural_fusion () { echo th neural_style.lua -style_image library/$1.jpg -content_image library/$content.jpg -num_iterations 1200 -gpu 0 -output_image library/output/$content/$content-$1.png} && neural_fusion abalone && neural_fusion beetle && neural_fusion blackmarble && neural_fusion blackpaper && neural_fusion blackscales && neural_fusion blacksilt && neural_fusion bluebluerust && neural_fusion Blueclothe && neural_fusion bluecrystal && neural_fusion bluedesert && neural_fusion bluerocks && neural_fusion bluesmoke && neural_fusion bluescales && neural_fusion bluerustrust && neural_fusion bluerust && neural_fusion canyon && neural_fusion clouddaylight && neural_fusion crazyflowers && neural_fusion crystal && neural_fusion crystalbluewaves && neural_fusion darkleaves && content=curiospixie &&  neural_fusion darkleaves &&  neural_fusion darkpalms &&  neural_fusion crows &&  neural_fusion ferns &&  neural_fusion fishscales &&  neural_fusion flatplants &&  neural_fusion flatflowers2 &&  neural_fusion flatflowers &&  neural_fusion glitchswirl &&  neural_fusion glitchswirlz &&  neural_fusion icecrystal &&  neural_fusion icecubes &&  neural_fusion lapis &&  neural_fusion japanneon &&  neural_fusion lichen &&  neural_fusion neb &&  neural_fusion ocean &&  neural_fusion oceancliff &&  neural_fusion noire &&  neural_fusion paintswirls &&  neural_fusion paintpaintswirls &&  neural_fusion paintgoop &&  neural_fusion paintart &&  neural_fusion pinkcrystals &&  neural_fusion pixelroses &&  neural_fusion pixelwaves &&  neural_fusion pixelworld &&  neural_fusion pomegrante &&  neural_fusion purplecanyon && content=rosegirl && neural_fusion blackmarble && neural_fusion blackpaper && neural_fusion blackscales && neural_fusion blacksilt && neural_fusion bluescales && neural_fusion bluerocks && neural_fusion bluesmoke && neural_fusion noire && neural_fusion darkleaves && neural_fusion darkpalms && neural_fusion ferns && neural_fusion farawaywaves && neural_fusion glitchswirl && neural_fusion glitchswirlz && neural_fusion glitchyglitchy && neural_fusion goldveins && neural_fusion greenbark && neural_fusion japanneon && neural_fusion oceancliff && neural_fusion sunsetglitch && neural_fusion sunset && neural_fusion stickerfun && neural_fusion redOctopus && neural_fusion purplehighcanyon && content=skull && neural_fusion blackmarble && neural_fusion blackpaper && neural_fusion blackscales && neural_fusion blacksilt && neural_fusion bluescales && neural_fusion bluerocks && neural_fusion bluesmoke && neural_fusion noire && neural_fusion darkleaves && neural_fusion darkpalms && neural_fusion ferns && neural_fusion farawaywaves && neural_fusion glitchswirl && neural_fusion glitchswirlz && neural_fusion glitchyglitchy && neural_fusion goldveins && neural_fusion greenbark && neural_fusion japanneon && neural_fusion oceancliff && neural_fusion sunsetglitch && neural_fusion sunset && neural_fusion stickerfun && neural_fusion redOctopus && neural_fusion purplehighcanyon && content=soph && neural_fusion blackmarble && neural_fusion blackpaper && neural_fusion blackscales && neural_fusion blacksilt && neural_fusion bluescales && neural_fusion bluerocks && neural_fusion bluesmoke && neural_fusion noire && neural_fusion darkleaves && neural_fusion darkpalms && neural_fusion ferns && neural_fusion farawaywaves && neural_fusion glitchswirl && neural_fusion glitchswirlz && neural_fusion glitchyglitchy && neural_fusion goldveins && neural_fusion greenbark && neural_fusion japanneon && neural_fusion oceancliff && neural_fusion sunsetglitch && neural_fusion sunset && neural_fusion stickerfun && neural_fusion redOctopus && neural_fusion purplehighcanyon && content=whitegirl && neural_fusion blackmarble && neural_fusion blackpaper && neural_fusion blackscales && neural_fusion blacksilt && neural_fusion bluescales && neural_fusion bluerocks && neural_fusion bluesmoke && neural_fusion noire && neural_fusion darkleaves && neural_fusion darkpalms && neural_fusion ferns && neural_fusion farawaywaves && neural_fusion glitchswirl && neural_fusion glitchswirlz && neural_fusion glitchyglitchy && neural_fusion goldveins && neural_fusion greenbark && neural_fusion japanneon && neural_fusion oceancliff && neural_fusion sunsetglitch && neural_fusion sunset && neural_fusion stickerfun && neural_fusion redOctopus && neural_fusion purplehighcanyon && content=wolfhowl && neural_fusion blackmarble && neural_fusion blackpaper && neural_fusion blackscales && neural_fusion blacksilt && neural_fusion bluescales && neural_fusion bluerocks && neural_fusion bluesmoke && neural_fusion noire && neural_fusion darkleaves && neural_fusion darkpalms && neural_fusion ferns && neural_fusion farawaywaves && neural_fusion glitchswirl && neural_fusion glitchswirlz && neural_fusion glitchyglitchy && neural_fusion goldveins && neural_fusion greenbark && neural_fusion japanneon && neural_fusion oceancliff && neural_fusion sunsetglitch && neural_fusion sunset && neural_fusion stickerfun && neural_fusion redOctopus && neural_fusion purplehighcanyon && content=qt && neural_fusion blackmarble && neural_fusion blackpaper && neural_fusion blackscales && neural_fusion blacksilt && neural_fusion bluescales && neural_fusion bluerocks && neural_fusion bluesmoke && neural_fusion noire && neural_fusion darkleaves && neural_fusion darkpalms && neural_fusion ferns && neural_fusion farawaywaves && neural_fusion glitchswirl && neural_fusion glitchswirlz && neural_fusion glitchyglitchy && neural_fusion goldveins && neural_fusion greenbark && neural_fusion japanneon && neural_fusion oceancliff && neural_fusion sunsetglitch && neural_fusion sunset && neural_fusion stickerfun && neural_fusion redOctopus && neural_fusion purplehighcanyon && content=punkgirl && neural_fusion blackmarble && neural_fusion blackpaper && neural_fusion blackscales && neural_fusion blacksilt && neural_fusion bluescales && neural_fusion bluerocks && neural_fusion bluesmoke && neural_fusion noire && neural_fusion darkleaves && neural_fusion darkpalms && neural_fusion ferns && neural_fusion farawaywaves && neural_fusion glitchswirl && neural_fusion glitchswirlz && neural_fusion glitchyglitchy && neural_fusion goldveins && neural_fusion greenbark && neural_fusion japanneon && neural_fusion oceancliff && neural_fusion sunsetglitch && neural_fusion sunset && neural_fusion stickerfun && neural_fusion redOctopus && neural_fusion purplehighcanyon && content=nightlife && neural_fusion blackmarble && neural_fusion blackpaper && neural_fusion blackscales && neural_fusion blacksilt && neural_fusion bluescales && neural_fusion bluerocks && neural_fusion bluesmoke && neural_fusion noire && neural_fusion darkleaves && neural_fusion darkpalms && neural_fusion ferns && neural_fusion farawaywaves && neural_fusion glitchswirl && neural_fusion glitchswirlz && neural_fusion glitchyglitchy && neural_fusion goldveins && neural_fusion greenbark && neural_fusion japanneon && neural_fusion oceancliff && neural_fusion sunsetglitch && neural_fusion sunset && neural_fusion stickerfun && neural_fusion redOctopus && neural_fusion purplehighcanyon && content=mandrill && neural_fusion blackmarble && neural_fusion blackpaper && neural_fusion blackscales && neural_fusion blacksilt && neural_fusion bluescales && neural_fusion bluerocks && neural_fusion bluesmoke && neural_fusion noire && neural_fusion darkleaves && neural_fusion darkpalms && neural_fusion ferns && neural_fusion farawaywaves && neural_fusion glitchswirl && neural_fusion glitchswirlz && neural_fusion glitchyglitchy && neural_fusion goldveins && neural_fusion greenbark && neural_fusion japanneon && neural_fusion oceancliff && neural_fusion sunsetglitch && neural_fusion sunset && neural_fusion stickerfun && neural_fusion redOctopus && neural_fusion purplehighcanyon && content=manmandrill && neural_fusion blackmarble && neural_fusion blackpaper && neural_fusion blackscales && neural_fusion blacksilt && neural_fusion bluescales && neural_fusion bluerocks && neural_fusion bluesmoke && neural_fusion noire && neural_fusion darkleaves && neural_fusion darkpalms && neural_fusion ferns && neural_fusion farawaywaves && neural_fusion glitchswirl && neural_fusion glitchswirlz && neural_fusion glitchyglitchy && neural_fusion goldveins && neural_fusion greenbark && neural_fusion japanneon && neural_fusion oceancliff && neural_fusion sunsetglitch && neural_fusion sunset && neural_fusion stickerfun && neural_fusion redOctopus && neural_fusion purplehighcanyon && content=mantis && neural_fusion blackmarble && neural_fusion blackpaper && neural_fusion blackscales && neural_fusion blacksilt && neural_fusion bluescales && neural_fusion bluerocks && neural_fusion bluesmoke && neural_fusion noire && neural_fusion darkleaves && neural_fusion darkpalms && neural_fusion ferns && neural_fusion farawaywaves && neural_fusion glitchswirl && neural_fusion glitchswirlz && neural_fusion glitchyglitch && neural_fusion goldveins && neural_fusion greenbark && neural_fusion japanneon && neural_fusion oceancliff && neural_fusion bluecrystal && neural_fusion bluedesert && content=maddude && neural_fusion blackmarble && neural_fusion blackpaper && neural_fusion blackscales && neural_fusion blacksilt && neural_fusion bluescales && neural_fusion bluerocks && neural_fusion bluesmoke && neural_fusion noire && neural_fusion darkleaves && neural_fusion darkpalms && neural_fusion ferns && neural_fusion farawaywaves && neural_fusion glitchswirl && neural_fusion glitchswirlz && neural_fusion glitchyglitchy && neural_fusion goldveins && neural_fusion greenbark && neural_fusion japanneon && neural_fusion oceancliff && content=jag && neural_fusion blackmarble && neural_fusion blackpaper && neural_fusion blackscales && neural_fusion blacksilt && neural_fusion bluescales && neural_fusion bluerocks && neural_fusion bluesmoke && neural_fusion noire && neural_fusion darkleaves && neural_fusion darkpalms && neural_fusion ferns && neural_fusion farawaywaves && neural_fusion glitchswirl && neural_fusion glitchswirlz && neural_fusion glitchyglitchy && neural_fusion goldveins && neural_fusion greenbark && neural_fusion japanneon && neural_fusion oceancliff && content=jagjag && neural_fusion blackmarble && neural_fusion blackpaper && neural_fusion blackscales && neural_fusion blacksilt && neural_fusion bluescales && neural_fusion bluerocks && neural_fusion bluesmoke && neural_fusion noire && neural_fusion darkleaves && neural_fusion darkpalms && neural_fusion ferns && neural_fusion farawaywaves && neural_fusion glitchswirl && neural_fusion glitchswirlz && neural_fusion glitchyglitchy && neural_fusion goldveins && neural_fusion greenbark && neural_fusion japanneon && neural_fusion oceancliff && content=hyenahaha && neural_fusion blackmarble && neural_fusion blackpaper && neural_fusion blackscales && neural_fusion blacksilt && neural_fusion bluescales && neural_fusion bluerocks && neural_fusion bluesmoke && neural_fusion noire && neural_fusion darkleaves && neural_fusion darkpalms && neural_fusion ferns && neural_fusion farawaywaves && neural_fusion glitchswirl && neural_fusion glitchswirlz && neural_fusion glitchyglitchy && neural_fusion goldveins && neural_fusion greenbark &&neural_fusion japanneon && neural_fusion oceancliff && content=hyenahahahaha && neural_fusion blackmarble && neural_fusion blackpaper && neural_fusion blackscales && neural_fusion blacksilt && neural_fusion bluescales && neural_fusion bluerocks && neural_fusion bluesmoke && neural_fusion noire && neural_fusion darkleaves && neural_fusion darkpalms && neural_fusion ferns && neural_fusion farawaywaves && neural_fusion glitchswirl && neural_fusion glitchswirlz && neural_fusion glitchyglitchy && neural_fusion goldveins && neural_fusion greenbark && neural_fusion japanneon && neural_fusion oceancliff && content=dinobird && neural_fusion paintart && neural_fusion oceandepths && neural_fusion neontokyo && neural_fusion muck && neural_fusion lichen && neural_fusion lichenrock && neural_fusion lapis && neural_fusion flatflowers && neural_fusion flatflowers2 && neural_fusion flatpalms && neural_fusion flatfield && neural_fusion ferns && neural_fusion crows && neural_fusion crazyflowers && neural_fusion bluecrystal && content=dinobirdfeathered && neural_fusion paintart && neural_fusion oceandepths && neural_fusion neontokyo && neural_fusion muck && neural_fusion lichen && neural_fusion lichenrock && neural_fusion lapis && neural_fusion flatflowers && neural_fusion flatflowers2 && neural_fusion flatpalms && neural_fusion flatfield && neural_fusion ferns && neural_fusion crows && neural_fusion crazyflowers && neural_fusion bluecrystal && content=birdo && neural_fusion paintart && neural_fusion oceandepths && neural_fusion neontokyo && neural_fusion muck && neural_fusion lichen && neural_fusion lichenrock && neural_fusion lapis && neural_fusion flatflowers && neural_fusion flatflowers2 && neural_fusion flatpalms && neural_fusion flatfield && neural_fusion ferns && neural_fusion crows && neural_fusion crazyflowers && neural_fusion bluecrystal && content=batqt neural_fusion blackmarble && neural_fusion blackpaper && neural_fusion blackscales && neural_fusion blacksilt && neural_fusion bluescales && neural_fusion bluerocks && neural_fusion bluesmoke && neural_fusion noire && neural_fusion darkleaves && neural_fusion darkpalms && neural_fusion ferns && neural_fusion farawaywaves && neural_fusion glitchswirl && neural_fusion glitchswirlz && neural_fusion glitchyglitchy && neural_fusion goldveins && neural_fusion greenbark && neural_fusion japanneon && neural_fusion oceancliff && neural_fusion sunsetglitch && neural_fusion sunset && neural_fusion stickerfun && neural_fusion redOctopus && neural_fusion purplehighcanyon`

**Comment by jcklpe** [comment]
Okay. Got it working. I cleaned up my script. Here's what it looks like:

```
function neural_fusion() {
th neural_style.lua -style_image library/$1.jpg -content_image library/$content.jpg -num_iterations 1200 -gpu 0 -output_image library/output/$content/$content-$1.png

};

content=asiangirl;
neural_fusion beetle;
neural_fusion blackmarble;
neural_fusion blackpaper;
neural_fusion blackscales;
neural_fusion blacksilt;
neural_fusion bluebluerust;
neural_fusion Blueclothe;
neural_fusion bluecrystal;
neural_fusion bluedesert;
neural_fusion bluerocks;
neural_fusion bluesmoke;
neural_fusion bluescales;
neural_fusion bluerustrust;
neural_fusion bluerust;
neural_fusion canyon;
neural_fusion clouddaylight;
neural_fusion crazyflowers;
neural_fusion crystal;
neural_fusion crystalbluewaves;
neural_fusion darkleaves;
neural_fusion darkpalms;
neural_fusion ferns;
neural_fusion farawaywaves;
neural_fusion glitchswirl;
neural_fusion glitchswirlz;
neural_fusion glitchyglitchy;
neural_fusion goldveins;
neural_fusion greenbark;
neural_fusion japanneon;
neural_fusion oceancliff;
neural_fusion sunsetglitch;
neural_fusion sunset;
neural_fusion stickerfun;
neural_fusion redOctopus;
neural_fusion purplehighcanyon;

content=batqt;
neural_fusion beetle;
neural_fusion blackmarble;
neural_fusion blackpaper;
neural_fusion blackscales;
neural_fusion blacksilt;
neural_fusion bluebluerust;
neural_fusion Blueclothe;
neural_fusion bluecrystal;
neural_fusion bluedesert;
neural_fusion bluerocks;
neural_fusion bluesmoke;
neural_fusion bluescales;
neural_fusion bluerustrust;
neural_fusion bluerust;
neural_fusion canyon;
neural_fusion clouddaylight;
neural_fusion crazyflowers;
neural_fusion crystal;
neural_fusion crystalbluewaves;
neural_fusion darkleaves;
neural_fusion darkpalms;
neural_fusion ferns;
neural_fusion farawaywaves;
neural_fusion glitchswirl;
neural_fusion glitchswirlz;
neural_fusion glitchyglitchy;
neural_fusion goldveins;
neural_fusion greenbark;
neural_fusion japanneon;
neural_fusion oceancliff;
neural_fusion sunsetglitch;
neural_fusion sunset;
neural_fusion stickerfun;
neural_fusion redOctopus;
neural_fusion purplehighcanyon;

```

**Comment by jcklpe** [comment]
Closing this as finished.
