### ISSUE TITLE
Which IDE for Lua?

### ISSUE THREAD

**Issue by xiaojidan** [jcjohnson/neural-style#46]
Hi all,
Recently, I turn to Torch, I am a newer. I want to know which tool you use in your project? I want to quickly to know it so that I can use Torch. Thank you for your advices.

**Comment by jcjohnson** [comment]
The only thing like an IDE that I use for Lua/Torch is iTorch, mostly as a superpowered interactive shell for development. For text editing I just use vim.

**Comment by xiaojidan** [comment]
Ok. Thanks a lot @jcjohnson
