### ISSUE TITLE
C# implementation

### ISSUE THREAD

**Issue by GlebSBrykin** [jcjohnson/neural-style#465]
Not an issue. I used Your code to implement the algorithm in C#. This can be extremely useful for Windows users. https://github.com/PABCSoft/NeuralArt/tree/English

**Comment by IdeaFactoryLabs** [comment]
Присоединяйтесь ко мне в разработке проекта с прибылью. Im задерживает
лучших из команды разработчиков по всему миру, чтобы предложить им
развивать нейронный двигатель. Я уже занимался всеми юридическими аспектами
проекта и защитил активы ...

**Comment by GlebSBrykin** [comment]
Можно подробнее?
