### ISSUE TITLE
General artistic style

### ISSUE THREAD

**Issue by MarcoROG** [jcjohnson/neural-style#5]
I premise i haven't read the paper yet. 
But one thing that comes to mind is that it'd be interesting to extract the style not from just one painting but from many of the same author.

**Comment by jcjohnson** [comment]
That would be cool, and might actually be doable with the current method. Instead of computing the target feature correlation matrix from one image, you could compute an aggregate correlation matrix from multiple images; once you have that then the rest of the code / method would be unchanged.

**Comment by MarcoROG** [comment]
I'm really new to all this, i know only the basics of machine learning and i'm pretty unfamiliar with Torch, but i'd love to understand more of this.
I'm writing a thesis for my last year in school and i'd like to feature this into my document as one of the examples and applications of machine learning if the creators of the project agree obviously

**Comment by jcjohnson** [comment]
That's fine with me.
