### ISSUE TITLE
Memory issue

### ISSUE THREAD

**Issue by vidyapriya13** [jcjohnson/neural-style#57]
I am trying to run the network on GTX 720 and i get the following issue 
  torch/install/share/lua/5.1/nn/utils.lua:11: cuda runtime error (2) : out of memory at /tmp/luarocks_cutorch-scm-1-2463/cutorch/lib/THC/THCStorage.cu:44
stack traceback:
    [C]: in function 'resize'
    torch/install/share/lua/5.1/nn/utils.lua:11: in function 'torch_Storage_type'
    torch/install/share/lua/5.1/nn/utils.lua:57: in function 'recursiveType'
    torch/install/share/lua/5.1/nn/Module.lua:123: in function 'type

I tried using smaller image_size and went to a size of 28 too. But it still doesn't work. Any suggestions what parameters I can tweak?

**Comment by hughperkins** [comment]
I have a 1GB card, and runs just fine.  I'm using the normalised vgg 19 though, not the original version.  normalised hsa no fc layers, which saves 450MB or so.

**Comment by vidyapriya13** [comment]
ok.. did you use the same hyper-parameters? The GTX 720 has 2GB. Any idea how much memory reducing an image size can save?

**Comment by hughperkins** [comment]
try these: https://github.com/jcjohnson/neural-style/issues/44#issuecomment-141936314

```
th neural_style.lua -style_image examples/inputs/picasso_selfport1907.jpg -content_image examples/inputs/brad_pitt.jpg -gpu 0 -output_image profile.png -image_size 200 -model_file models/vgg_normalised.caffemodel -num_iterations 1000 -save_iter 50 -normalize_gradients -content_weight 50000 -style_weight 90000
```

**Comment by vidyapriya13** [comment]
Well I guess the issue lies elsewhere. As i get the same error at cuda runtime error (2) : out of memory at /tmp/luarocks_cutorch-scm-1-2463/cutorch/lib/THC/THCStorage.cu:44.

**Comment by hughperkins** [comment]
Ah, then I'm out of ideas.  (other than basic things like: did you make sure to upgrade all of: nn, torch7, cutorch, cunn, inn? are you using cuda7?) (oh wait, is this gpu being used for your display/monitor too?  is it possible that your monitor usage is somehow using all your memory?  maybe you can use `nvidia-smi` to check how much memory is available when neural_style is not runnign?)

**Comment by vidyapriya13** [comment]
Yikes. Some process was clogging 1.5GB of the memory. Seems to be running fine now when I restarted my system. Thanks.

**Comment by hughperkins** [comment]
:-)
