### ISSUE TITLE
Nothing Happens after successfully loading models/VGG_ILSVRC_19_layers.caffemodel

### ISSUE THREAD

**Issue by masarmor** [jcjohnson/neural-style#59]
I have to say your work is a magnificent piece of art, giving life to those artists again is what we always thought can happen only in movies.
i would like to ask for a tip, I installed neural-style and have been trying to run th neural_style.lua -gpu -1 -print_iter -1 on Ubuntu 14.04, typical buffer size warnings appear and the execution stops without any further details.

![untitled](https://cloud.githubusercontent.com/assets/15029562/10362429/93c9e9de-6de9-11e5-86b7-efd6d4289409.jpg)

According to what i have found most of the executions start iterating through convolutions but nothing appeared in my case.

P.S i am not using GPU, i tried different image sizes and i tried omitting the "require 'nn' require 'cunn'" from the model file.

**Comment by dodekeract** [comment]
I'm guessing it finished calculating what you told it to calculate. You didn't specify any iteration amount and told it to never print any information by using `print_iter -1`.

**Comment by masarmor** [comment]
It took 1 second to finish processing and i assume there was something wrong while i see no output image although i - in one attempt- tried to set the image name.

**Comment by masarmor** [comment]
It took 1 second to finish processing and i assume there was something
wrong while i see no output image although i - in one attempt- tried to set
the image name.

**Comment by jcjohnson** [comment]
With the flag `-print_iter -1` it won't print anything; can you try `-print_iter 1` instead? Also did it create a file `out.png`? If not then I suspect that the optimization is not converging and thus terminating early; you may need to increase the `-content_weight`.

**Comment by masarmor** [comment]
It was something with the a machine itself, i moved my working environment to a more robust machine and all went fine! 
thanks for assisting
