### ISSUE TITLE
Segmentation fault on resolution >2000px

### ISSUE THREAD

**Issue by anastasiuspernat** [jcjohnson/neural-style#64]
When trying to generate images with more than 2000px width it just crashes with the message "Segmentation fault (core dumped)". When it doesn't have enough memory it usually says something "Get more RAM" - but this time it doesn't.

I'm using a configuration with 244GB RAM so I hope it's quite enough. I also tried source/style images 800px, 1000px, 1500px and 3000px - it doesn't make a difference, the same crash.

I was able to generate images with less than 2000px with on the same config - cpu mode of course.

**Comment by anastasiuspernat** [comment]
Fixed it with the following Pull request:
https://github.com/torch/nn/pull/443

Bug was caused by Torch/nn

**Comment by djdjoko** [comment]
Hi,
did you get it to run on high resolution? Are you using a GPU and what optimizer are you running?

**Comment by JeffCrusey** [comment]
im having trouble getting much past 1000px, crashes every time
