### ISSUE TITLE
Cannot Reproduce Examples

### ISSUE THREAD

**Issue by brewiss** [jcjohnson/neural-style#9]
Hello,

First off, great work with the implementation. I'm just wondering why I can't reproduce your examples. 

Given: $ th neural_style.lua -style_image picasso.jpg -content_image brad_pitt.jpg 

The output contains strange noise:
![out](https://cloud.githubusercontent.com/assets/14096104/9637872/24004e5c-5158-11e5-9ba6-746ecec7d975.png)

This problem persists with other images as well. My guess is that the problem is caused by the warning I'm receiving in terminal: 
                                                    
[libprotobuf WARNING google/protobuf/io/coded_stream.cc:505] Reading dangerously large protocol message.  If the message turns out to be larger than 1073741824 bytes, parsing will be halted for security reasons.  To increase the limit (or to disable these warnings), see CodedInputStream::SetTotalBytesLimit() in google/protobuf/io/coded_stream.h.
[libprotobuf WARNING google/protobuf/io/coded_stream.cc:78] The total number of bytes read was 574671192
Successfully loaded models/VGG_ILSVRC_19_layers.caffemodel
conv1_1: 64 3 3 3
conv1_2: 64 64 3 3
conv2_1: 128 64 3 3
conv2_2: 128 128 3 3
conv3_1: 256 128 3 3
conv3_2: 256 256 3 3
conv3_3: 256 256 3 3
conv3_4: 256 256 3 3
conv4_1: 512 256 3 3
conv4_2: 512 512 3 3
conv4_3: 512 512 3 3
conv4_4: 512 512 3 3
conv5_1: 512 512 3 3
conv5_2: 512 512 3 3
conv5_3: 512 512 3 3
conv5_4: 512 512 3 3
fc6: 1 1 25088 4096
fc7: 1 1 4096 4096
fc8: 1 1 4096 1000
WARNING: Skipping content loss	

My system specs are as follows:  
ubuntu 14.04 LTS
cuda 7
Torch7
GTX TITAN X

Help would be appreciated.

**Comment by jnordberg** [comment]
See #6 Your torch image library is outdated

**Comment by brewiss** [comment]
Thank You! Fixed!
