### ISSUE TITLE
GPU vs GPU with cudnn backend 

### ISSUE THREAD

**Issue by filmo** [jcjohnson/neural-style#92]
I'm using a Geforce 980ti,  i7-5930K CPU with 16GB of ram, running Ubuntu 14.04

Running 
```th neural_style.lua -gpu 0 -print_iter 1```

took 1 minute 55 seconds

```
Iteration 1000 / 1000	
  Content 1 loss: 630264.414062	
  Style 1 loss: 175.963569	
  Style 2 loss: 2303.931046	
  Style 3 loss: 3840.511703	
  Style 4 loss: 135616.809082	
  Style 5 loss: 569.020891	
  Total loss: 772770.650353	
<optim.lbfgs> 	reached max number of iterations	

real	1m55.523s
user	0m34.636s
sys	1m22.292s
```

running:
```th neural_style.lua -gpu 0 -backend cudnn```

Is taking about 2 minute and 22 seconds. It seems like it spends a lot of time on the 'creating recyclable buffers':

```
Setting up style layer  	30	:	relu5_1	
WARNING: Skipping content loss	
Running optimization with L-BFGS	
<optim.lbfgs> 	creating recyclable direction/step/history buffers	
Iteration 50 / 1000	
  Content 1 loss: 966463.359375	
  Style 1 loss: 23537.689209	
  Style 2 loss: 153309.521484	
  Style 3 loss: 32727.481079	
  Style 4 loss: 308508.862305	

--- snip ---

  Style 5 loss: 565.189457	
  Total loss: 773580.600133	
<optim.lbfgs> 	reached max number of iterations	

real	2m21.514s
user	0m50.088s
sys	1m33.400s
```

I was expecting the cudnn backend to be faster. Are these little tests from install a bad way to evaluate this? Or am I doing something wrong? 

It does seem to reduce the model size on the GPU from about 2.8 GB to 1.5 GB when I use cudnn backend.

**Comment by sheerun** [comment]
Isn't "creating buffers" action one-time only?

**Comment by jcjohnson** [comment]
For Maxwell the default cudnn algorithms don't work very well; you need to add the line `cudnn.benchmark = true` after you import cudnn.

**Comment by filmo** [comment]
Sorry, I'm not clear on where to add this flag in the code base. I didn't see an import statement in neural_style.lua but on line 60 I see:

```
  if params.backend == 'cudnn' then
    require 'cudnn'
    cudnn.SpatialConvolution.accGradParameters = nn.SpatialConvolutionMM.accGradParameters -- ie: nop
  end
```

Should I add ```cudnn.benchmark = true``` after the ```require 'cudnn'``` line?

(I'm just getting started with torch and lua, so I'm unsure where to make this change.)

Thank you for your help.

**Comment by jcjohnson** [comment]
Yep, add it right after the `require 'cudnn'` line.

**Comment by ryanpamplin** [comment]
@filmo Is it faster now with the changes?

**Comment by filmo** [comment]
It does not appear to be faster with cudnn. Actually seems slower with cudnn backend. However memory usages is much lower, so in theory one can work with larger images though I haven't tried that yet.

3119MB w/o cudnn (1 minute 52 seconds)

1778MB w/cudnn (2 minutes 9 seconds)

Reduces memory usage by about 45%
