### ISSUE TITLE
Limitation of max image size is 512? 

### ISSUE THREAD

**Issue by MelodyHai** [jcjohnson/neural-style#95]
I want to get a sharper image to I set the param image_size to 1024, however, the latter half image is totally gray. Then I change image_size to 640 and 768, still some part of the output image is gray. So I guess maybe there is a max limitation?
And if it is true, is there an easy way to modify the code?
Thank you

**Comment by jcjohnson** [comment]
There is no limitation on image size other than your available memory and patience; however you may need to use different parameters for larger images. If you are seeing flat image regions then you might trt removing the TV regularization (`-tv_weight 0`)
